const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "reader.html"), "utf8");
const settings = fs.readFileSync(path.join(root, "reader-settings-ui.js"), "utf8");
const reader = fs.readFileSync(path.join(root, "reader.js"), "utf8");
const preferences = fs.readFileSync(path.join(root, "reader-preferences-ui.js"), "utf8");
const clickZones = fs.readFileSync(path.join(root, "reader-click-zones-ui.js"), "utf8");
const clickZonesCss = fs.readFileSync(path.join(root, "reader-click-zones.css"), "utf8");
const annotations = fs.readFileSync(path.join(root, "reader-page-annotations.js"), "utf8");
const notes = fs.readFileSync(path.join(root, "reader-notes-ui.js"), "utf8");
const layout = fs.readFileSync(path.join(root, "reader-page-layout.js"), "utf8");
const pagination = fs.readFileSync(path.join(root, "reader-page-pagination.js"), "utf8");
const runtime = fs.readFileSync(path.join(root, "reader-page-runtime.js"), "utf8");
const i18n = fs.readFileSync(path.join(root, "reader-i18n.js"), "utf8");
const shell = fs.readFileSync(path.join(root, "reader-shell-state.js"), "utf8");
const preferencesCss = fs.readFileSync(path.join(root, "reader-preferences.css"), "utf8");

test("reader settings exposes a dedicated preferences window above quick controls", () => {
  assert.match(html, /id="reader-preferences-btn"[\s\S]*?阅读偏好/);
  assert.match(html, /id="reader-preferences-modal"/);
  assert.match(html, /data-pref-panel="appearance"/);
  assert.match(html, /data-pref-panel="pagination"/);
  assert.match(html, /data-pref-panel="toolbar"/);
  assert.match(html, /data-pref-panel="advanced"/);
  assert.match(html, /reader-preferences-ui\.js/);
  assert.match(shell, /PREFERENCES: "preferences"/);
});

test("quick settings keep frequent reading controls while detailed controls live in preferences", () => {
  const quickStart = html.indexOf('<div id="settings"');
  const preferencesStart = html.indexOf('<div id="reader-preferences-modal"');
  const toolbarStart = html.indexOf('data-pref-panel="toolbar"');
  const advancedStart = html.indexOf('data-pref-panel="advanced"');
  const quick = html.slice(quickStart, preferencesStart);
  const paginationPanel = html.slice(html.indexOf('data-pref-panel="pagination"'), toolbarStart);
  const toolbarPanel = html.slice(toolbarStart, advancedStart);

  for (const id of ["reader-quick-palette", "set-font", "set-size", "set-line", "set-dual-mode", "set-scroll-mode", "quick-tts-btn", "quick-set-ttssrc", "quick-set-ttsrate"]) {
    assert.match(quick, new RegExp(`id="${id}"`));
  }
  for (const id of ["set-style-mode", "set-note-size", "set-para", "set-letter", "set-turnfx", "set-turnspeed", "set-mt", "set-mb", "set-ml", "set-mr", "set-ttssrc", "set-ttsrate"]) {
    assert.doesNotMatch(quick, new RegExp(`id="${id}"`));
  }
  for (const id of ["set-style-mode", "set-note-size", "set-para", "set-letter", "set-turnfx", "set-turnspeed", "set-mt", "set-mb", "set-ml", "set-mr"]) {
    assert.match(paginationPanel, new RegExp(`id="${id}"`));
  }
  assert.match(toolbarPanel, /id="set-ttssrc"/);
  assert.match(toolbarPanel, /id="set-ttsrate"/);
  assert.match(preferencesCss, /reader-preference-compact-list/);
  assert.match(preferencesCss, /reader-preference-margin-grid/);
});

test("quick settings place the compact and classic switch beside the preferences launch", () => {
  assert.match(html, /id="settings" class="settings" data-quick-ui-mode="compact"/);
  const quickStart = html.indexOf('<div id="settings"');
  const preferencesStart = html.indexOf('<div id="reader-preferences-modal"');
  const quick = html.slice(quickStart, preferencesStart);
  const preferences = html.slice(preferencesStart);
  assert.match(quick, /class="reader-quick-header"[\s\S]*?id="reader-preferences-btn"[\s\S]*?data-quick-ui-mode-option="compact"[\s\S]*?data-quick-ui-mode-option="classic"/);
  assert.match(quick, /class="reader-quick-classic-only"[\s\S]*?id="quick-set-style-mode"[\s\S]*?id="quick-set-turnspeed"/);
  assert.doesNotMatch(preferences, /reader-quick-layout-group|quickSettingsLayout|data-quick-ui-mode-option/);
  assert.doesNotMatch(html, /reader-quick-layout-preview/);
  assert.match(quick, /id="quick-set-ttsrate"[\s\S]*?id="quick-set-ttssrc"[\s\S]*?id="quick-tts-btn"/);
  assert.match(settings, /bindSel\("quick-set-ttssrc", "ttsSource"\)/);
  assert.match(settings, /quickSettingsModeKey = "readerQuickSettingsUiMode"/);
  assert.match(settings, /function connectQuickMirror\(proxyId, sourceId, proxyOutputId, sourceOutputId\)/);
  assert.match(settings, /connectQuickMirror\("quick-set-style-mode", "set-style-mode"\)/);
  assert.match(settings, /document\.getElementById\("quick-tts-btn"\)\?\.addEventListener\("click"/);
});

test("advanced preferences configure the independent jump-back icon lifetime", () => {
  assert.match(html, /data-pref-panel="advanced"[\s\S]*?data-pref-bool="showReaderJumpBack"/);
  assert.match(html, /id="pref-reader-jump-back-settings"/);
  assert.doesNotMatch(html, /data-pref-panel="advanced"[\s\S]*?data-reader-i18n="advancedHint"/);
  assert.doesNotMatch(html, /data-pref-panel="advanced"[\s\S]*?data-reader-i18n="readerJumpBackHint"/);
  assert.match(preferences, /global\.addEventListener\("click", \(event\) => \{/);
  assert.match(preferences, /config\.contains\(event\.target\) \|\| readerJumpBackSettingsButton\?\.contains\(event\.target\)/);
  assert.match(preferences, /setReaderJumpBackConfigExpanded\(false\)/);
  assert.match(preferences, /if \(expanded\) renderJumpBackPreview\(global\.ReaderSettings\.get\(\)\)/);
  assert.match(html, /id="pref-reader-jump-back-dismiss-mode"[\s\S]*?value="pages"[\s\S]*?value="time"/);
  assert.match(html, /id="pref-reader-jump-back-pages"[^>]*min="1"[^>]*max="100"/);
  assert.match(html, /id="pref-reader-jump-back-seconds"[^>]*min="1"[^>]*max="600"/);
  assert.match(html, /id="pref-reader-jump-back-size"[^>]*min="30"[^>]*max="160"[^>]*step="1"/);
  assert.match(html, /id="pref-reader-jump-back-preview"/);
  assert.match(html, /id="pref-reader-jump-back-preview-icon"[^>]*><svg class="reader-jump-back-arrow" viewBox="0 0 120 48"/);
  assert.match(settings, /showReaderJumpBack: true/);
  assert.match(settings, /readerJumpBackDismissMode: "pages"/);
  assert.match(settings, /readerJumpBackDismissSeconds: 30/);
  assert.match(settings, /readerJumpBackDismissPages: 3/);
  assert.match(settings, /readerJumpBackSizeLevel: 1/);
  assert.match(settings, /readerJumpBackIconSizePx: 32/);
  assert.match(settings, /readerJumpBackPositionX: 950/);
  assert.match(settings, /readerJumpBackPositionY: 500/);
  assert.match(settings, /app_settings_sync_get/);
  assert.match(settings, /app_settings_sync_save/);
  assert.match(settings, /app-settings-synced/);
  assert.match(settings, /remote\?\.exists/);
  assert.match(settings, /readerLayoutSettings: normalizedReaderLayoutSettings\(settings\)/);
  assert.match(settings, /hasReaderLayoutSettings/);
  assert.match(settings, /fontFamily/);
  assert.match(settings, /dualPageGap/);
  assert.match(settings, /imagePagination/);
  assert.match(preferences, /readerJumpBackDismissMode: event\.target\.value === "time" \? "time" : "pages"/);
  assert.match(preferences, /readerJumpBackDismissPages: value/);
  assert.match(preferences, /readerJumpBackDismissSeconds: value/);
  assert.match(preferences, /readerJumpBackIconSizePx: value/);
  assert.match(preferences, /readerJumpBackPositionX/);
  assert.match(preferences, /pointerdown/);
  assert.match(preferences, /const jumpBackSettings = global\.ReaderSettings\.get\(\)/);
  assert.match(preferences, /renderJumpBackPreview\(jumpBackSettings\)/);
  assert.match(preferences, /global\.addEventListener\("pointermove", moveJumpBackPreviewDrag, true\)/);
  assert.match(preferences, /global\.addEventListener\("pointerup", finishJumpBackPreviewDrag, true\)/);
  assert.match(preferences, /function jumpBackPreviewTrackPoint\(length, iconSize, hitSize, position\)/);
  assert.match(preferences, /function jumpBackPreviewPositionFromPoint\(point, length, iconSize\)/);
  assert.match(preferences, /function jumpBackIconHeight\(iconSizePx\)/);
  assert.match(preferences, /const hitTargetInset = Math\.max\(0, hitSize - iconSize\) \/ 2/);
  assert.match(preferences, /jumpBackIconPixels\(value\).*px/);
  assert.match(preferencesCss, /reader-preference-settings-button/);
  assert.match(preferencesCss, /reader-jump-back-config/);
  assert.match(preferencesCss, /reader-jump-back-preview/);
  assert.match(preferencesCss, /reader-jump-back-preview-icon\{[^}]*background:transparent[^}]*color:#315f9f[^}]*box-shadow:none/s);
});

test("preference navigation uses localized collapse labels and only shows section icons when collapsed", () => {
  assert.match(html, /id="reader-preferences-nav-toggle"/);
  assert.match(preferences, /translated && translated !== key \? translated : fallback/);
  assert.match(i18n, /collapsePreferenceNavigation: "收起分类"/);
  assert.match(i18n, /expandPreferenceNavigation: "展开分类"/);
  assert.match(preferencesCss, /\.reader-preferences-nav button\[data-pref-section\] \.reader-preferences-nav-icon\{display:none\}/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed \.reader-preferences-nav button\[data-pref-section\] \.reader-preferences-nav-icon\{display:grid\}/);
});

test("preference categories collapse to one icon rail and preserve all four sections", () => {
  assert.match(html, /<\/nav>\s*<button id="reader-preferences-nav-toggle"[^>]*aria-expanded="true"[^>]*aria-label="收起分类"/);
  assert.match(html, /data-pref-section="appearance"[\s\S]*?data-pref-section="pagination"[\s\S]*?data-pref-section="toolbar"[\s\S]*?data-pref-section="advanced"/);
  assert.match(html, /reader-preferences-nav-icon/);
  assert.match(preferences, /PREFERENCE_NAV_COLLAPSED_KEY = "readerPreferencesNavCollapsed"/);
  assert.match(preferences, /function applyPreferenceNavState\(\)/);
  assert.match(preferences, /preferencesCard\?\.classList\.toggle\("nav-collapsed", preferenceNavCollapsed\)/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed \.reader-preferences-body/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed \.reader-preferences-nav-label/);
  assert.match(preferencesCss, /\.reader-preferences-nav-toggle\{position:absolute/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed #reader-preferences-nav-toggle\{left:62px!important\}/);
  assert.match(html, /reader-preferences-nav-toggle-collapse[\s\S]*?reader-preferences-nav-toggle-expand/);
  assert.match(preferencesCss, /\.reader-preferences-nav-toggle-expand\{display:none\}/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed \.reader-preferences-nav-toggle-expand\{display:block\}/);
  assert.match(preferencesCss, /#reader-preferences-nav-toggle\{top:50%!important;left:172px!important/);
  assert.match(preferencesCss, /\.reader-preferences-card\.nav-collapsed \.reader-preferences-nav button\{width:38px;min-height:38px;padding:6px\}/);
  assert.doesNotMatch(html, /data-pref-panel="appearance">\s*<h3/);
  assert.doesNotMatch(html, /data-pref-panel="pagination">\s*<h3/);
  assert.doesNotMatch(html, /data-pref-panel="toolbar">\s*<h3/);
  assert.doesNotMatch(html, /data-pref-panel="advanced">\s*<h3/);
});

test("appearance defaults use a restrained palette and reset custom colors at the lower right", () => {
  assert.match(preferences, /link: "#2f6fad", selection: "#dceafa", footnote: "#f3f6fa", border: "#b7c7da"/);
  assert.match(preferences, /link: "#9abfe8", selection: "#3a4f6b", footnote: "#252f3a", border: "#647a94"/);
  assert.match(preferences, /backgroundPreset: "light", customPaletteId: "", customBackgroundColor: "#fffdf8"/);
  assert.match(preferences, /linkColor: "", selectionColor: "", footnoteBackground: "", footnoteBorder: "", theme: "light"/);
  assert.doesNotMatch(preferences, /pref-reset-colors[^\n]*textColor: ""/);
  assert.match(html, /class="reader-appearance-actions"[\s\S]*?id="pref-reset-colors"[\s\S]*?恢复默认/);
  assert.match(html, /reader-appearance-actions\{display:flex;justify-content:flex-end/);
  assert.match(preferencesCss, /\.reader-palette-grid\{grid-template-columns:repeat\(4,minmax\(0,1fr\)\);gap:10px\}/);
});
test("preferences preserve old themes and update the same local reader settings object", () => {
  assert.match(settings, /if \(!stored\.backgroundPreset && \["light", "dark", "sepia"\]\.includes\(stored\.theme\)\)/);
  assert.match(settings, /window\.ReaderSettings = Object\.freeze/);
  assert.match(settings, /reader-settings-changed/);
  assert.match(preferences, /updateAppearance/);
  assert.match(settings, /readerBookAppearanceV1/);
  assert.match(preferences, /FileReader/);
  assert.match(preferences, /movePaletteDrag/);
  assert.match(html, /data-pref-scope="default"[^>]*>总体</);
  assert.match(html, /id="reader-preferences-close"/);
  assert.match(preferences, /preferencesOutsidePointerDown/);
  assert.match(preferences, /activeColorControl/);
  assert.match(preferences, /function openColorPopover\(control\)/);
  assert.match(preferences, /function setActiveColor\(value\)/);
  assert.match(html, /id="reader-color-popover"/);
  assert.match(html, /class="reader-color-picker" type="button" data-pref-color="textColor"/);
  assert.match(html, /data-pref-color-swatch="#f44336"/);
  assert.match(html, /data-pref-color-swatch="#0f766e"/);
  assert.doesNotMatch(html, /type="color" data-pref-color/);
  assert.match(preferencesCss, /\.reader-color-popover\{position:fixed/);
  assert.match(preferencesCss, /background:var\(--color\)!important/);
  assert.match(preferences, /MAX_CUSTOM_PALETTES = 15/);
  assert.match(preferences, /function paintColorPreset\(button\)/);
  assert.match(preferences, /event\.stopImmediatePropagation\(\)/);
  assert.doesNotMatch(html, /默认总体设置/);
  assert.doesNotMatch(html, /独立设置/);
  assert.doesNotMatch(html, /pref-scope-hint/);
  assert.match(html, /data-pref-scope="book"/);
  assert.match(html, /id="pref-palette-grid"/);
  assert.match(html, /id="pref-background-image"/);
  assert.match(html, /id="pref-add-palette"/);
  assert.match(html, /id="pref-palette-name"/);
  assert.doesNotMatch(html, /添加当前配色/);
  assert.match(html, /id="reader-quick-palette"/);
  assert.match(html, /reader-preferences-btn[\s\S]*?reader-quick-palette[\s\S]*?set-font/);
  assert.doesNotMatch(html, /class="theme-btn"/);
  assert.match(html, /data-pref-bool="showTextConversion"/);
  assert.match(html, /data-pref-bool="showChapterButtons"/);
  assert.match(settings, /showChapterButtons: true/);
  assert.match(html, /data-pref-bool="showVocabularyButton"/);
  assert.match(settings, /showVocabularyButton: true/);
  assert.match(settings, /getElementById\("vocab-btn"\).*toggleAttribute\("hidden", settings\.showVocabularyButton === false\)/);
  assert.match(settings, /getElementById\("prev-btn"\).*toggleAttribute\("hidden", hideChapterButtons\)/);
  assert.match(settings, /getElementById\("next-btn"\).*toggleAttribute\("hidden", hideChapterButtons\)/);
  assert.match(html, /\.toolbar > \[hidden\] \{ display: none !important; \}/);
  assert.match(html, /\.settings \.mode-toggle-item\[hidden\] \{ display: none !important; \}/);
  assert.match(html, /data-pref-bool="showPageInfo"/);
});

test("EPUB preferences distinguish whole-image and continuous image pagination", () => {
  assert.match(html, /id="pref-image-pagination" class="reader-pagination-choice-grid" role="radiogroup"/);
  assert.match(html, /data-image-pagination="next-page"[\s\S]*?data-image-pagination="continuous"/);
  assert.doesNotMatch(html, /<select id="pref-image-pagination"/);
  assert.match(preferences, /querySelectorAll\("\[data-image-pagination\]"\)/);
  assert.match(preferencesCss, /\.reader-pagination-card\{[^}]*border-radius:13px[^}]*background:linear-gradient/s);
  assert.match(preferencesCss, /\.reader-pagination-choice\.active\{[^}]*background:#edf5ff/s);
  assert.match(layout, /footnoteBackground/);
  assert.match(layout, /footnoteBorder/);
  assert.match(layout, /两种图片过渡方式共享同一份正文分页规则/);
  assert.doesNotMatch(layout, /if\(S\.imagePagination/);
  assert.match(layout, /break-inside:avoid/);
  assert.match(layout, /imagePagination:"next-page"/);
  assert.match(layout, /el\.complete&&el\.naturalWidth>0/);
  assert.match(runtime, /“下一页完整显示”不能创建任何视觉预览/);
  assert.match(runtime, /if\(S\.imagePagination!=='continuous'\)\{clearPagedImagePreview\(\);return;\}/);
  assert.match(runtime, /function probeNextPagedImage\(pr,current,step\)/);
  assert.match(runtime, /root\.style\.transform='translateX\(-'/);
  assert.match(runtime, /inFutureColumn&&page===current\+1/);
  assert.match(runtime, /function hasPagedTextBeforeMedia\(lines,rootRect,step,page,mediaTop\)/);
  assert.match(runtime, /nearPageTop\|\|mediaIsNextContent/);
  assert.match(runtime, /pagedImagePreview\.parentNode!==document\.body/);
  assert.match(runtime, /position:fixed;display:none/);
  assert.match(runtime, /function visiblePagedTextBottom\(pr\)/);
  assert.match(runtime, /candidate\.__kpPagedPreviewHeight=crop/);
  assert.match(runtime, /var imagePaginationChanged=/);
  assert.match(runtime, /var imagePaginationOnly=/);
  assert.match(runtime, /if\(imagePaginationOnly\)\{/);
  assert.match(runtime, /tracePagedImageLayout\('setting_deferred'/);
  assert.match(reader, /window\.ReaderLayoutPreview = Object\.freeze/);
  assert.match(reader, /flowMode: "paged",[\s\S]*pageMode: "dual"/);
  assert.match(preferences, /function ensureReaderLayoutPreview\(\)/);
  assert.match(preferences, /document\.createElement\("iframe"\)/);
  assert.match(preferences, /allow-scripts allow-same-origin/);
  assert.match(preferences, /global\.ReaderLayoutPreview\?\.source\?\./);
  assert.match(preferences, /event\.source !== readerLayoutPreviewFrame\.contentWindow/);
  assert.match(preferences, /reader-preferences-layout-preview/);
  assert.match(preferences, /reader-preference-preview-cutout-left/);
  assert.doesNotMatch(preferences, /ALICE_PREVIEW_IMAGE|ALICE_PREVIEW_TEXT/);
  assert.match(preferencesCss, /\.reader-preferences-layout-preview\{position:fixed;inset:0;z-index:51/);
  assert.match(preferencesCss, /-webkit-mask-composite:xor/);
  assert.match(preferencesCss, /reader-preferences-layout-preview-frame/);
  assert.doesNotMatch(preferences, /is-gutter-adjusting/);
  assert.doesNotMatch(preferencesCss, /is-gutter-adjusting/);
  assert.match(layout, /max-height:calc\(100vh/);
  assert.match(layout, /transition:none !important/);
  assert.match(layout, /scroll-behavior:auto !important;scroll-snap-type:none !important/);
  assert.match(settings, /reader-theme-instant/);
  assert.match(settings, /MAX_INLINE_BACKGROUND_IMAGE_CHARS/);
  assert.match(settings, /sanitizeBackgroundImage/);
  assert.match(layout, /bgImage=.*background/);
  assert.doesNotMatch(layout, /backgroundImageValue\.length<=MAX_INLINE_BACKGROUND_IMAGE_CHARS/);
});

test("two-page pagination exposes a bounded configurable gutter", () => {
  assert.match(html, /id="pref-dual-page-gap"[^>]*min="0"[^>]*max="120"[^>]*step="1"/);
  assert.match(html, /id="pref-dual-page-gap-reset"[^>]*data-reader-i18n="restoreDualPageGap"/);
  assert.match(settings, /dualPageGap: 40/);
  assert.match(settings, /Math\.max\(0, Math\.min\(120, Math\.round\(dualPageGap\)\)\)/);
  assert.match(preferences, /ReaderSettings\.update\(\{ dualPageGap: value \}, \{ deferPageApply: true \}\)/);
  assert.match(preferences, /ReaderSettings\.applyDeferredSettings\?\.\(\)/);
  assert.match(settings, /applyDeferredSettings\(\) \{ pushSettings\(\); \}/);
  assert.match(runtime, /var dualPageGapOnly=/);
  assert.match(runtime, /if\(dualPageGapOnly&&!isDualPage\(\)\)return;/);
  assert.match(preferences, /type: "dual-page-gap", dualPageGap: value, phase: "adjusting"/);
  assert.match(preferences, /id="pref-dual-page-gap-value"|pref-dual-page-gap-value/);
  assert.match(pagination, /S\.dualPageGap/);
  assert.match(pagination, /function dualPageGapPx\(\)/);
  assert.match(pagination, /var gap=dualPageGapPx\(\)/);
  assert.match(pagination, /S\.marginRight,S\.dualPageGap,S\.pageMode/);
  assert.match(i18n, /dualPageGap: "Two-page gutter"/);
  assert.match(i18n, /dualPageGap: "双页中缝"/);
  assert.match(i18n, /restoreDualPageGap: "恢复默认"/);
  assert.match(preferencesCss, /reader-preference-range-control/);
  assert.match(preferences, /function renderReaderLayoutPreview\(\{ phase, dualPageGap \}\)/);
  assert.match(preferences, /READER_LAYOUT_PREVIEW_REVEAL_DELAY = 160/);
  assert.match(preferences, /function revealReaderLayoutPreviewAfterPaint\(\)/);
  assert.match(preferences, /readerLayoutPreview\.hidden \|\| readerLayoutPreview\.dataset\.source !== source/);
  assert.match(preferences, /DEFAULT_DUAL_PAGE_GAP/);
  assert.match(preferences, /dualPageGap: detail\.dualPageGap/);
  assert.match(preferencesCss, /\.reader-preferences-layout-preview/);
  assert.match(preferencesCss, /mask-composite:exclude/);
});

test("appearance supports book overrides, saved palettes, image backgrounds, and animated reordering", () => {
  assert.match(settings, /readerBookAppearanceV1/);
  assert.match(settings, /updateAppearance/);
  assert.match(settings, /setBookContext/);
  assert.match(preferences, /readerCustomPalettesV1/);
  assert.match(preferences, /readerPaletteOrderV1/);
  assert.match(preferences, /FileReader/);
  assert.match(preferences, /style\.transition = "transform \.18s cubic-bezier/);
  assert.match(preferences, /renderQuickPalettes/);
  assert.match(preferences, /function quickPaletteScope\(\)/);
  assert.match(preferences, /hasBookAppearance\?\.\(\) \? "book" : "default"/);
  assert.match(preferences, /function applyQuickPalette\(palette\)/);
  assert.match(preferences, /applyQuickPalette\(palette\)/);
  assert.match(preferences, /paletteList\(\)\.slice\(0, 3\)/);
  assert.match(preferences, /pointerdown/);
  assert.match(preferences, /reader-palette-placeholder/);
  assert.match(preferences, /animatePaletteInsert/);
  assert.match(preferencesCss, /reader-preferences-launch span\[aria-hidden="true"\]\{display:grid;width:30px/);
  assert.doesNotMatch(preferencesCss, /\.reader-preferences-launch span\{display:grid/);
  assert.match(preferencesCss, /width:640px/);
  assert.match(preferencesCss, /#reader-preferences-modal \.reader-preferences-card\{[^}]*overflow:hidden/);
  assert.match(preferencesCss, /reader-preferences-body\{[^}]*height:520px[^}]*min-height:0/);
  assert.match(preferencesCss, /reader-preferences-content\{[^}]*min-height:0[^}]*overflow:auto/);
  assert.match(preferencesCss, /flex:0 0 640px/);
  assert.match(preferencesCss, /align-items:center/);
  assert.match(preferencesCss, /justify-content:center/);
  assert.match(preferences, /paletteLabel\(palette\)\.slice\(0, 2\)/);
  assert.match(preferences, /function applyPalettePreview/);
  assert.match(preferences, /safePaletteImage/);
  assert.match(preferences, /applyPalettePreview\(button, palette\)/);
  assert.match(preferences, /applyPalettePreview\(tile, palette\)/);
  assert.match(preferences, /function appendPaletteReadingPreview/);
  assert.match(preferences, /reader-palette-preview-selection/);
  assert.match(preferences, /春风又绿江南岸/);
  assert.match(preferences, /function updateAutomaticPreviewTheme/);
  assert.match(preferences, /autoPreviewThemeId/);
  assert.doesNotMatch(preferences, /colorPickerDialogUntil/);
  assert.match(preferences, /text: current\.textColor/);
  assert.match(preferences, /link: current\.linkColor/);
  assert.match(preferences, /selection: current\.selectionColor/);
  assert.match(preferences, /footnote: current\.footnoteBackground/);
  assert.match(preferences, /border: current\.footnoteBorder/);
  assert.match(preferencesCss, /reader-palette-tile\.has-background-image/);
  assert.match(preferencesCss, /reader-palette-reading-preview/);
  assert.match(preferencesCss, /reader-palette-preview-selection/);
  assert.match(preferencesCss, /reader-palette-preview-footnote/);
  assert.match(preferencesCss, /font-size:14px/);
  assert.match(preferencesCss, /background-size:cover/);
  assert.match(preferences, /const choosePalette = !state\.moved \? state\.choose : null/);
  assert.match(preferencesCss, /aspect-ratio:1/);
  assert.match(preferences, /MAX_CUSTOM_PALETTES = 15/);
  assert.match(preferences, /backgroundAssetId/);
  assert.match(preferences, /cache_reader_background_image/);
  assert.doesNotMatch(preferences, /function resizeBackgroundImage/);
  assert.match(preferencesCss, /reader-palette-scroll\.has-many-palettes\{padding:2px 10px 10px 2px\}/);
  assert.doesNotMatch(preferencesCss, /reader-palette-scroll\.has-many-palettes\{[^}]*overflow-y/);
  assert.match(html, /id="reader-preferences-scrollbar"/);
  assert.match(html, /id="reader-preferences-scroll-thumb"/);
  assert.match(preferencesCss, /reader-preferences-content::\-webkit-scrollbar\{display:none/);
  assert.match(preferencesCss, /reader-preferences-scroll-thumb/);
  assert.match(preferences, /function updatePreferencesScrollbar/);
  assert.match(preferences, /preferencesScrollThumb\.setPointerCapture/);
  assert.doesNotMatch(preferences, /function routePaletteWheel/);
  assert.doesNotMatch(preferences, /innerTarget - innerStart/);
  assert.doesNotMatch(preferences, /addEventListener\("wheel", routePaletteWheel/);
  assert.doesNotMatch(preferencesCss, /resize:vertical/);
  assert.match(preferencesCss, /reader-palette-delete/);
  assert.match(preferences, /beginPaletteNameEdit/);
  assert.match(preferences, /removeCustomPalette/);
  assert.match(preferences, /event\.target === modal/);
  assert.match(preferences, /reader-palette-reading-preview/);
  assert.match(preferences, /ReaderSettings\.update\(\{ imagePagination/);
  assert.match(preferences, /ReaderSettings\.update\(\{ \[input\.dataset\.prefBool\]/);
  assert.match(settings, /Object\.entries\(bookAppearance\)\.filter\(\(\[key\]\) => READER_APPEARANCE_KEYS\.has\(key\)\)/);
  assert.match(settings, /Object\.entries\(patch \|\| \{\}\)\.filter\(\(\[key\]\) => READER_APPEARANCE_KEYS\.has\(key\)\)/);
  assert.match(layout, /customBackgroundImage/);
});

test("two-page gutter is a precise, dual-mode-only pagination preference", () => {
  const pagination = fs.readFileSync(path.join(root, "reader-page-pagination.js"), "utf8");
  assert.match(html, /id="pref-dual-page-gap"[^>]*min="0"[^>]*max="120"[^>]*step="1"/);
  assert.match(html, /data-reader-i18n="dualPageGap"[\s\S]*?data-reader-i18n="dualPageGapHint"/);
  assert.match(preferences, /function dualPageGapPixels\(value\)/);
  assert.match(preferences, /ReaderSettings\.update\(\{ dualPageGap: value \}, \{ deferPageApply: true \}\)/);
  assert.match(settings, /dualPageGap: 40/);
  assert.match(settings, /Math\.max\(0, Math\.min\(120, Math\.round\(dualPageGap\)\)\)/);
  assert.match(layout, /dualPageGap:40/);
  assert.match(pagination, /function dualPageGapPx\(\)\{[\s\S]*?Math\.max\(0,Math\.min\(120,v\)\)/);
  assert.match(pagination, /if\(isDualPage\(\)\)\{[\s\S]*?var gap=dualPageGapPx\(\)/);
  assert.match(layout, /var trailingColumnLeak=Math\.max\(0,pl\.r-pl\.gap\)/);
  assert.match(layout, /var dualClip='inset\(0 '\+trailingColumnLeak\+'px 0 0\)'/);
  assert.match(layout, /pager\.style\.clipPath=dualClip/);
});

test("page margins are grouped with typography details instead of using a separate card", () => {
  const typography = html.match(/data-reader-i18n="typographyDetails"[\s\S]*?data-reader-i18n="pageTurnExperience"/)?.[0] || "";
  assert.match(typography, /reader-preference-margin-section/);
  assert.match(typography, /id="set-mt"[\s\S]*?id="set-mb"[\s\S]*?id="set-ml"[\s\S]*?id="set-mr"/);
  assert.match(preferencesCss, /reader-preference-margin-section \.reader-preference-margin-grid\{padding:0\}/);
});

test("reading display settings are separated from toolbar function menus", () => {
  assert.match(html, /reader-reading-display-group[\s\S]*?data-pref-bool="showTextConversion"[\s\S]*?data-pref-bool="showPageInfo"/);
  assert.match(html, /<details class="reader-preference-group reader-toolbar-menu-group">[\s\S]*?<summary class="reader-preference-group-head"><h4 data-reader-i18n="toolbarFunctionMenu"/);
  assert.match(html, /reader-toolbar-menu-group[\s\S]*?id="reader-toolbar-order-list"[\s\S]*?data-pref-bool="showTocButton"[\s\S]*?data-pref-bool="showVocabularyButton"/);
  assert.doesNotMatch(html, /reader-toolbar-menu-group[\s\S]*?toolbarFunctionMenuHint/);
  assert.doesNotMatch(html, /reader-toolbar-menu-group[\s\S]*?data-pref-bool="showTextConversion"/);
  assert.match(html, /data-reader-i18n="readingDisplay"/);
  assert.match(html, /data-reader-i18n="toolbarFunctionMenu"/);
  assert.match(preferencesCss, /reader-preference-group-head/);
  assert.match(preferencesCss, /\.reader-toolbar-menu-group>summary\{display:flex/);
});

test("pagination and toolbar panels begin directly with their settings", () => {
  assert.doesNotMatch(html, /data-pref-panel="pagination" hidden>\s*<p class="reader-preference-hint reader-pagination-intro"/);
  assert.doesNotMatch(html, /data-pref-panel="toolbar" hidden>\s*<p class="reader-preference-hint" data-reader-i18n="toolbarDisplayHint"/);
  assert.match(html, /data-pref-panel="pagination" hidden>\s*<div class="reader-pagination-layout">/);
  assert.match(html, /data-pref-panel="toolbar" hidden>\s*<section class="reader-preference-group reader-reading-display-group">/);
});

test("toolbar and advanced panels use the lightweight preference design", () => {
  assert.match(html, /reader-reading-display-group[\s\S]*?class="settings-switch"[\s\S]*?data-pref-bool="showTextConversion"/);
  assert.match(html, /data-pref-panel="advanced"[\s\S]*?class="reader-preference-group reader-advanced-group"/);
  assert.match(html, /class="reader-advanced-main-row"[\s\S]*?class="reader-advanced-icon"[\s\S]*?id="pref-reader-jump-back-config"/);
  assert.match(preferencesCss, /\.reader-toolbar-order-item\{[^}]*min-height:47px[^}]*border:0[^}]*background:transparent[^}]*box-shadow:none/s);
  assert.match(preferencesCss, /\.reader-advanced-main-row\{[^}]*grid-template-columns:38px minmax\(0,1fr\) auto/s);
  assert.match(preferencesCss, /\.reader-advanced-group \.reader-jump-back-config\{[^}]*margin:0[^}]*border-top:1px solid #e8edf4/s);
  assert.match(clickZonesCss, /\.reader-click-zone-actions\{display:flex;justify-content:flex-end/);
  assert.match(clickZonesCss, /\.reader-click-zone-reset\{[^}]*border-color:transparent[^}]*background:transparent/s);
});

test("toolbar function cards reorder the live reader toolbar with animated avoidance", () => {
  assert.match(html, /data-toolbar-item="toc"[\s\S]*data-toolbar-item="chapters"[\s\S]*data-toolbar-item="tts"[\s\S]*data-toolbar-item="annotations"[\s\S]*data-toolbar-item="vocabulary"[\s\S]*data-toolbar-item="settings"/);
  assert.match(html, /data-toolbar-item="settings"[\s\S]*?<input type="checkbox" checked disabled data-toolbar-required/);
  assert.match(html, /id="reader-settings-toolbar-item" class="gear-wrap"/);
  assert.match(settings, /READER_TOOLBAR_ITEM_IDS = Object\.freeze\(\["toc", "chapters", "tts", "annotations", "vocabulary", "settings"\]\)/);
  assert.match(settings, /toolbarOrder: READER_TOOLBAR_ITEM_IDS\.slice\(\)/);
  assert.match(settings, /function normalizedReaderToolbarOrder\(value\)/);
  assert.match(settings, /function applyReaderToolbarOrder\(value\)/);
  assert.match(settings, /toolbar\.insertBefore\(element, anchor\)/);
  assert.match(settings, /applyReaderToolbarOrder\(settings\.toolbarOrder\)/);
  assert.match(preferences, /function animateToolbarPlaceholder\(state, beforeNode\)/);
  assert.match(preferences, /item\.style\.transform = `translateY\(\$\{dy\}px\)`/);
  assert.match(preferences, /function moveToolbarDrag\(event\)/);
  assert.match(preferences, /function finishToolbarDrag\(event\)/);
  assert.match(preferences, /ReaderSettings\.update\(\{ toolbarOrder: toolbarOrderFromList\(list\) \}\)/);
  assert.match(preferencesCss, /\.reader-toolbar-order-item\.dragging/);
  assert.match(preferencesCss, /\.reader-toolbar-order-placeholder/);
  assert.match(preferencesCss, /input:disabled:checked\+\.settings-slider\{background:#b8c0cb\}/);
});

test("reader preferences draw non-overlapping zones directly on the canvas", () => {
  assert.match(html, /href="reader-click-zones\.css"/);
  assert.match(html, /id="reader-click-zone-preview"[^>]*role="application"/);
  assert.match(html, /id="reader-click-zone-canvas"/);
  assert.match(html, /id="reader-click-zone-preset"[\s\S]*?id="reader-click-zone-preset-name"[\s\S]*?id="reader-click-zone-preset-new"[\s\S]*?id="reader-click-zone-preset-save"[\s\S]*?id="reader-click-zone-preset-delete"/);
  assert.doesNotMatch(html, /id="reader-click-zone-redraw"/);
  assert.doesNotMatch(html, /id="reader-click-zone-add"/);
  assert.match(html, /id="reader-click-zone-reset"/);
  assert.match(html, /src="reader-click-zones-ui\.js"/);
  assert.match(settings, /DEFAULT_READER_CLICK_ZONES = Object\.freeze/);
  assert.match(settings, /action: "prev", x: 0, y: 0, width: 400, height: 1000/);
  assert.match(settings, /action: "center", x: 400, y: 0, width: 200, height: 1000/);
  assert.match(settings, /action: "next", x: 600, y: 0, width: 400, height: 1000/);
  assert.match(settings, /clickZones: DEFAULT_READER_CLICK_ZONES\.map/);
  assert.match(settings, /function normalizedReaderClickZones\(value\)/);
  assert.match(settings, /MAX_READER_CLICK_ZONES = 12/);
  assert.match(clickZones, /const MAX_PRESETS = 12/);
  assert.match(clickZones, /const PRESET_STORAGE_KEY = "readerClickZonePresetsV1"/);
  assert.match(clickZones, /function normalizePresets\(value, fallbackZones\)/);
  assert.match(clickZones, /function syncActivePreset\(\)/);
  assert.match(clickZones, /presetSelect\.addEventListener\("change"/);
  assert.match(clickZones, /presetNewButton\.addEventListener\("click"/);
  assert.match(clickZones, /presetSaveButton\.addEventListener\("click"/);
  assert.match(clickZones, /presetDeleteButton\.addEventListener\("click"/);
  assert.match(i18n, /clickZonePreset: "操作方案"/);
  assert.match(settings, /source\.map\(\(raw, index\) => \{/);
  assert.match(settings, /function readerZonesOverlap\(a, b\)/);
  assert.match(settings, /function removeReaderZoneOverlaps\(source\)/);
  assert.match(settings, /return removeReaderZoneOverlaps\(normalized\)/);
  assert.match(settings, /clickActionAt\(clientX, clientY, width, height\)/);
  assert.match(clickZones, /const ACTIONS = Object\.freeze\(\["prev", "center", "next", "none"\]\)/);
  assert.match(clickZones, /function drawnRectangle\(start, point\)/);
  assert.match(clickZones, /function resizedRectangle\(zone, handle, point\)/);
  assert.doesNotMatch(clickZones, /state\.mode === "draw"/);
  assert.match(clickZones, /state\.mode === "resize"/);
  assert.match(clickZones, /target \? "move" : "create"/);
  assert.match(clickZones, /function candidateAllowed\(candidate, id\)/);
  assert.match(clickZones, /function applyCandidate\(state, candidate\)/);
  assert.match(clickZones, /state\.mode === "create"/);
  assert.doesNotMatch(clickZones, /redrawArmed|reader-click-zone-redraw/);
  assert.match(clickZones, /if \(!state\.moved\) return/);
  assert.match(clickZones, /openOnRelease = !state\.moved && state\.mode === "move"/);
  assert.match(clickZones, /if \(!state\.moved && state\.mode === "create"\)/);
  assert.match(clickZones, /zones = zones\.filter\(\(zone\) => zone\.id !== state\.zone\.id\)/);
  assert.match(clickZones, /function createActionPopover\(zone, index\)/);
  assert.match(clickZones, /button\.dataset\.zoneAction = action/);
  assert.match(clickZones, /zones = zones\.filter\(\(item\) => item\.id !== zone\.id\)/);
  assert.match(clickZones, /zones = zones\.concat\(zone\)/);
  assert.doesNotMatch(clickZones, /reader-click-zone-add/);
  assert.match(clickZones, /global\.ReaderSettings\.update\(\{ clickZones:/);
  assert.match(clickZonesCss, /\.reader-click-zone\.active/);
  assert.match(clickZonesCss, /\.reader-click-zone-handle\.handle-se/);
  assert.match(clickZonesCss, /\.reader-click-zone-popover/);
  assert.match(clickZonesCss, /\.reader-click-zone-action-grid/);
  assert.match(annotations, /function tapActionAt\(x,y\)/);
  assert.match(annotations, /supplied\.length\?supplied:defaults/);
  assert.match(annotations, /function overlaps\(a,b\)/);
  assert.match(annotations, /var accepted=\[\]/);
  assert.doesNotMatch(annotations, /matches\.sort/);
  assert.match(annotations, /if\(tapAction==='next'\)/);
  assert.match(annotations, /else if\(tapAction==='prev'\)/);
  assert.match(annotations, /else if\(tapAction==='center'\)/);
  assert.match(annotations, /else readerBugTrace\('click','none',e\)/);
  assert.doesNotMatch(annotations, /window\.innerWidth\*0\.4/);
  assert.match(notes, /ReaderSettings\?\.clickActionAt/);
});
