const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const html = fs.readFileSync(path.join(root, "reader.html"), "utf8");
const settings = fs.readFileSync(path.join(root, "reader-settings-ui.js"), "utf8");
const preferences = fs.readFileSync(path.join(root, "reader-preferences-ui.js"), "utf8");
const layout = fs.readFileSync(path.join(root, "reader-page-layout.js"), "utf8");
const pagination = fs.readFileSync(path.join(root, "reader-page-pagination.js"), "utf8");
const runtime = fs.readFileSync(path.join(root, "reader-page-runtime.js"), "utf8");
const i18n = fs.readFileSync(path.join(root, "reader-i18n.js"), "utf8");
const shell = fs.readFileSync(path.join(root, "reader-shell-state.js"), "utf8");
const preferencesCss = fs.readFileSync(path.join(root, "reader-preferences.css"), "utf8");

test("reader settings exposes a dedicated preferences window above quick controls", () => {
  assert.match(html, /id="reader-preferences-btn"[\s\S]*?阅读偏好/);
  assert.match(html, /id="reader-preferences-modal"/);
  assert.match(html, /data-pref-panel="appearance"/);
  assert.match(html, /data-pref-panel="pagination"/);
  assert.match(html, /data-pref-panel="toolbar"/);
  assert.match(html, /data-pref-panel="advanced"/);
  assert.match(html, /reader-preferences-ui\.js/);
  assert.match(shell, /PREFERENCES: "preferences"/);
});

test("advanced preferences configure the independent jump-back icon lifetime", () => {
  assert.match(html, /data-pref-panel="advanced"[\s\S]*?data-pref-bool="showReaderJumpBack"/);
  assert.match(html, /id="pref-reader-jump-back-settings"/);
  assert.doesNotMatch(html, /data-pref-panel="advanced"[\s\S]*?data-reader-i18n="advancedHint"/);
  assert.doesNotMatch(html, /data-pref-panel="advanced"[\s\S]*?data-reader-i18n="readerJumpBackHint"/);
  assert.match(preferences, /global\.addEventListener\("click", \(event\) => \{/);
  assert.match(preferences, /config\.contains\(event\.target\) \|\| readerJumpBackSettingsButton\?\.contains\(event\.target\)/);
  assert.match(preferences, /setReaderJumpBackConfigExpanded\(false\)/);
  assert.match(preferences, /if \(expanded\) renderJumpBackPreview\(global\.ReaderSettings\.get\(\)\)/);
  assert.match(html, /id="pref-reader-jump-back-dismiss-mode"[\s\S]*?value="pages"[\s\S]*?value="time"/);
  assert.match(html, /id="pref-reader-jump-back-pages"[^>]*min="1"[^>]*max="100"/);
  assert.match(html, /id="pref-reader-jump-back-seconds"[^>]*min="1"[^>]*max="600"/);
  assert.match(html, /id="pref-reader-jump-back-size"[^>]*min="30"[^>]*max="160"[^>]*step="1"/);
  assert.match(html, /id="pref-reader-jump-back-preview"/);
  assert.match(html, /id="pref-reader-jump-back-preview-icon"[^>]*><svg class="reader-jump-back-arrow" viewBox="0 0 120 48"/);
  assert.match(settings, /showReaderJumpBack: true/);
  assert.match(settings, /readerJumpBackDismissMode: "pages"/);
  assert.match(settings, /readerJumpBackDismissSeconds: 30/);
  assert.match(settings, /readerJumpBackDismissPages: 3/);
  assert.match(settings, /readerJumpBackSizeLevel: 1/);
  assert.match(settings, /readerJumpBackIconSizePx: 32/);
  assert.match(settings, /readerJumpBackPositionX: 950/);
  assert.match(settings, /readerJumpBackPositionY: 500/);
  assert.match(settings, /app_settings_sync_get/);
  assert.match(settings, /app_settings_sync_save/);
  assert.match(settings, /app-settings-synced/);
  assert.match(settings, /remote\?\.exists/);
  assert.match(preferences, /readerJumpBackDismissMode: event\.target\.value === "time" \? "time" : "pages"/);
  assert.match(preferences, /readerJumpBackDismissPages: value/);
  assert.match(preferences, /readerJumpBackDismissSeconds: value/);
  assert.match(preferences, /readerJumpBackIconSizePx: value/);
  assert.match(preferences, /readerJumpBackPositionX/);
  assert.match(preferences, /pointerdown/);
  assert.match(preferences, /const jumpBackSettings = global\.ReaderSettings\.get\(\)/);
  assert.match(preferences, /renderJumpBackPreview\(jumpBackSettings\)/);
  assert.match(preferences, /global\.addEventListener\("pointermove", moveJumpBackPreviewDrag, true\)/);
  assert.match(preferences, /global\.addEventListener\("pointerup", finishJumpBackPreviewDrag, true\)/);
  assert.match(preferences, /function jumpBackPreviewTrackPoint\(length, iconSize, hitSize, position\)/);
  assert.match(preferences, /function jumpBackPreviewPositionFromPoint\(point, length, iconSize\)/);
  assert.match(preferences, /function jumpBackIconHeight\(iconSizePx\)/);
  assert.match(preferences, /const hitTargetInset = Math\.max\(0, hitSize - iconSize\) \/ 2/);
  assert.match(preferences, /jumpBackIconPixels\(value\).*px/);
  assert.match(preferencesCss, /reader-preference-settings-button/);
  assert.match(preferencesCss, /reader-jump-back-config/);
  assert.match(preferencesCss, /reader-jump-back-preview/);
  assert.match(preferencesCss, /reader-jump-back-preview-icon\{[^}]*background:transparent[^}]*color:#315f9f[^}]*box-shadow:none/s);
});

test("appearance defaults use a restrained palette and reset custom colors at the lower right", () => {
  assert.match(preferences, /link: "#2f6fad", selection: "#dceafa", footnote: "#f3f6fa", border: "#b7c7da"/);
  assert.match(preferences, /link: "#9abfe8", selection: "#3a4f6b", footnote: "#252f3a", border: "#647a94"/);
  assert.match(preferences, /backgroundPreset: "light", customPaletteId: "", customBackgroundColor: "#fffdf8"/);
  assert.match(preferences, /linkColor: "", selectionColor: "", footnoteBackground: "", footnoteBorder: "", theme: "light"/);
  assert.doesNotMatch(preferences, /pref-reset-colors[^\n]*textColor: ""/);
  assert.match(html, /class="reader-appearance-actions"[\s\S]*?id="pref-reset-colors"[\s\S]*?恢复默认/);
  assert.match(html, /reader-appearance-actions\{display:flex;justify-content:flex-end/);
});
test("preferences preserve old themes and update the same local reader settings object", () => {
  assert.match(settings, /if \(!stored\.backgroundPreset && \["light", "dark", "sepia"\]\.includes\(stored\.theme\)\)/);
  assert.match(settings, /window\.ReaderSettings = Object\.freeze/);
  assert.match(settings, /reader-settings-changed/);
  assert.match(preferences, /updateAppearance/);
  assert.match(settings, /readerBookAppearanceV1/);
  assert.match(preferences, /FileReader/);
  assert.match(preferences, /movePaletteDrag/);
  assert.match(html, /data-pref-scope="default"[^>]*>总体</);
  assert.doesNotMatch(html, /id="reader-preferences-close"/);
  assert.doesNotMatch(html, /默认总体设置/);
  assert.doesNotMatch(html, /独立设置/);
  assert.doesNotMatch(html, /pref-scope-hint/);
  assert.match(html, /data-pref-scope="book"/);
  assert.match(html, /id="pref-palette-grid"/);
  assert.match(html, /id="pref-background-image"/);
  assert.match(html, /id="pref-add-palette"/);
  assert.match(html, /id="pref-palette-name"/);
  assert.doesNotMatch(html, /添加当前配色/);
  assert.match(html, /id="reader-quick-palette"/);
  assert.match(html, /reader-preferences-btn[\s\S]*?reader-quick-palette[\s\S]*?set-font/);
  assert.doesNotMatch(html, /class="theme-btn"/);
  assert.match(html, /data-pref-bool="showTextConversion"/);
  assert.match(html, /data-pref-bool="showChapterButtons"/);
  assert.match(settings, /showChapterButtons: true/);
  assert.match(html, /data-pref-bool="showVocabularyButton"/);
  assert.match(settings, /showVocabularyButton: true/);
  assert.match(settings, /getElementById\("vocab-btn"\).*toggleAttribute\("hidden", settings\.showVocabularyButton === false\)/);
  assert.match(settings, /getElementById\("prev-btn"\).*toggleAttribute\("hidden", hideChapterButtons\)/);
  assert.match(settings, /getElementById\("next-btn"\).*toggleAttribute\("hidden", hideChapterButtons\)/);
  assert.match(html, /\.toolbar > \[hidden\] \{ display: none !important; \}/);
  assert.match(html, /\.settings \.mode-toggle-item\[hidden\] \{ display: none !important; \}/);
  assert.match(html, /data-pref-bool="showPageInfo"/);
});

test("EPUB preferences distinguish whole-image and continuous image pagination", () => {
  assert.match(layout, /footnoteBackground/);
  assert.match(layout, /footnoteBorder/);
  assert.match(layout, /两种图片过渡方式共享同一份正文分页规则/);
  assert.doesNotMatch(layout, /if\(S\.imagePagination/);
  assert.match(layout, /break-inside:avoid/);
  assert.match(layout, /imagePagination:"next-page"/);
  assert.match(layout, /el\.complete&&el\.naturalWidth>0/);
  assert.match(runtime, /S\.imagePagination!=='continuous'&&S\.imagePagination!=='next-page'/);
  assert.match(runtime, /if\(S\.imagePagination!=='continuous'\)\{clearPagedImagePreview\(\);return;\}/);
  assert.match(runtime, /function probeNextPagedImage\(pr,current,step\)/);
  assert.match(runtime, /root\.style\.transform='translateX\(-'/);
  assert.match(runtime, /inFutureColumn&&page===current\+1/);
  assert.match(runtime, /function hasPagedTextBeforeMedia\(lines,rootRect,step,page,mediaTop\)/);
  assert.match(runtime, /nearPageTop\|\|mediaIsNextContent/);
  assert.match(runtime, /pagedImagePreview\.parentNode!==document\.body/);
  assert.match(runtime, /position:fixed;display:none/);
  assert.match(runtime, /function visiblePagedTextBottom\(pr\)/);
  assert.match(runtime, /candidate\.__kpPagedPreviewHeight=crop/);
  assert.match(runtime, /var imagePaginationChanged=/);
  assert.match(runtime, /var imagePaginationOnly=/);
  assert.match(runtime, /if\(imagePaginationOnly\)\{/);
  assert.match(runtime, /tracePagedImageLayout\('setting_deferred'/);
  assert.match(layout, /max-height:calc\(100vh/);
  assert.match(layout, /transition:none !important/);
  assert.match(settings, /reader-theme-instant/);
  assert.match(settings, /MAX_INLINE_BACKGROUND_IMAGE_CHARS/);
  assert.match(settings, /sanitizeBackgroundImage/);
  assert.match(layout, /bgImage=.*background/);
  assert.doesNotMatch(layout, /backgroundImageValue\.length<=MAX_INLINE_BACKGROUND_IMAGE_CHARS/);
});

test("two-page pagination exposes a bounded configurable gutter", () => {
  assert.match(html, /id="pref-dual-page-gap"[^>]*min="0"[^>]*max="120"[^>]*step="1"/);
  assert.match(settings, /dualPageGap: 40/);
  assert.match(settings, /Math\.max\(0, Math\.min\(120, Math\.round\(dualPageGap\)\)\)/);
  assert.match(preferences, /ReaderSettings\.update\(\{ dualPageGap: value \}\)/);
  assert.match(preferences, /id="pref-dual-page-gap-value"|pref-dual-page-gap-value/);
  assert.match(pagination, /S\.dualPageGap/);
  assert.match(pagination, /function dualPageGapPx\(\)/);
  assert.match(pagination, /var gap=dualPageGapPx\(\)/);
  assert.match(pagination, /S\.marginRight,S\.dualPageGap,S\.pageMode/);
  assert.match(i18n, /dualPageGap: "Two-page gutter"/);
  assert.match(i18n, /dualPageGap: "双页中缝"/);
  assert.match(preferencesCss, /reader-preference-range-control/);
});

test("appearance supports book overrides, saved palettes, image backgrounds, and animated reordering", () => {
  assert.match(settings, /readerBookAppearanceV1/);
  assert.match(settings, /updateAppearance/);
  assert.match(settings, /setBookContext/);
  assert.match(preferences, /readerCustomPalettesV1/);
  assert.match(preferences, /readerPaletteOrderV1/);
  assert.match(preferences, /FileReader/);
  assert.match(preferences, /style\.transition = "transform \.18s cubic-bezier/);
  assert.match(preferences, /renderQuickPalettes/);
  assert.match(preferences, /function quickPaletteScope\(\)/);
  assert.match(preferences, /hasBookAppearance\?\.\(\) \? "book" : "default"/);
  assert.match(preferences, /function applyQuickPalette\(palette\)/);
  assert.match(preferences, /applyQuickPalette\(palette\)/);
  assert.match(preferences, /paletteList\(\)\.slice\(0, 3\)/);
  assert.match(preferences, /pointerdown/);
  assert.match(preferences, /reader-palette-placeholder/);
  assert.match(preferences, /animatePaletteInsert/);
  assert.match(preferencesCss, /reader-preferences-launch span\[aria-hidden="true"\]\{display:grid;width:30px/);
  assert.doesNotMatch(preferencesCss, /\.reader-preferences-launch span\{display:grid/);
  assert.match(preferencesCss, /width:640px/);
  assert.match(preferencesCss, /#reader-preferences-modal \.reader-preferences-card\{[^}]*overflow:hidden/);
  assert.match(preferencesCss, /reader-preferences-body\{[^}]*height:520px[^}]*min-height:0/);
  assert.match(preferencesCss, /reader-preferences-content\{[^}]*min-height:0[^}]*overflow:auto/);
  assert.match(preferencesCss, /flex:0 0 640px/);
  assert.match(preferencesCss, /align-items:center/);
  assert.match(preferencesCss, /justify-content:center/);
  assert.match(preferences, /paletteLabel\(palette\)\.slice\(0, 2\)/);
  assert.match(preferences, /function applyPalettePreview/);
  assert.match(preferences, /safePaletteImage/);
  assert.match(preferences, /applyPalettePreview\(button, palette\)/);
  assert.match(preferences, /applyPalettePreview\(tile, palette\)/);
  assert.match(preferencesCss, /reader-palette-tile\.has-background-image/);
  assert.match(preferencesCss, /background-size:cover/);
  assert.match(preferences, /const choosePalette = !state\.moved \? state\.choose : null/);
  assert.match(preferencesCss, /aspect-ratio:1/);
  assert.match(preferences, /MAX_CUSTOM_PALETTES = 10/);
  assert.match(preferences, /backgroundAssetId/);
  assert.match(preferences, /cache_reader_background_image/);
  assert.doesNotMatch(preferences, /function resizeBackgroundImage/);
  assert.match(preferencesCss, /reader-palette-scroll\.has-many-palettes\{padding:2px 10px 10px 2px\}/);
  assert.doesNotMatch(preferencesCss, /reader-palette-scroll\.has-many-palettes\{[^}]*overflow-y/);
  assert.match(html, /id="reader-preferences-scrollbar"/);
  assert.match(html, /id="reader-preferences-scroll-thumb"/);
  assert.match(preferencesCss, /reader-preferences-content::\-webkit-scrollbar\{display:none/);
  assert.match(preferencesCss, /reader-preferences-scroll-thumb/);
  assert.match(preferences, /function updatePreferencesScrollbar/);
  assert.match(preferences, /preferencesScrollThumb\.setPointerCapture/);
  assert.doesNotMatch(preferences, /function routePaletteWheel/);
  assert.doesNotMatch(preferences, /innerTarget - innerStart/);
  assert.doesNotMatch(preferences, /addEventListener\("wheel", routePaletteWheel/);
  assert.doesNotMatch(preferencesCss, /resize:vertical/);
  assert.match(preferencesCss, /reader-palette-delete/);
  assert.match(preferences, /beginPaletteNameEdit/);
  assert.match(preferences, /removeCustomPalette/);
  assert.match(preferences, /event\.target === modal/);
  assert.doesNotMatch(preferences, /reader-palette-preview/);
  assert.match(preferences, /ReaderSettings\.update\(\{ imagePagination/);
  assert.match(preferences, /ReaderSettings\.update\(\{ \[input\.dataset\.prefBool\]/);
  assert.match(settings, /Object\.entries\(bookAppearance\)\.filter\(\(\[key\]\) => READER_APPEARANCE_KEYS\.has\(key\)\)/);
  assert.match(settings, /Object\.entries\(patch \|\| \{\}\)\.filter\(\(\[key\]\) => READER_APPEARANCE_KEYS\.has\(key\)\)/);
  assert.match(layout, /customBackgroundImage/);
});

test("two-page gutter is a precise, dual-mode-only pagination preference", () => {
  const pagination = fs.readFileSync(path.join(root, "reader-page-pagination.js"), "utf8");
  assert.match(html, /id="pref-dual-page-gap"[^>]*min="0"[^>]*max="120"[^>]*step="1"/);
  assert.match(html, /data-reader-i18n="dualPageGap"[\s\S]*?data-reader-i18n="dualPageGapHint"/);
  assert.match(preferences, /function dualPageGapPixels\(value\)/);
  assert.match(preferences, /ReaderSettings\.update\(\{ dualPageGap: value \}\)/);
  assert.match(settings, /dualPageGap: 40/);
  assert.match(settings, /Math\.max\(0, Math\.min\(120, Math\.round\(dualPageGap\)\)\)/);
  assert.match(layout, /dualPageGap:40/);
  assert.match(pagination, /function dualPageGapPx\(\)\{[\s\S]*?Math\.max\(0,Math\.min\(120,v\)\)/);
  assert.match(pagination, /if\(isDualPage\(\)\)\{[\s\S]*?var gap=dualPageGapPx\(\)/);
});
