// 主窗口本地化的单一入口。新增界面只需加 data-i18n，不把语言选择变成
// 只有下拉框、没有实际界面变化的假设置。
(function (global) {
  const STORAGE_KEY = "appLanguageV1";
  const LANGUAGES = [
    ["system", "跟随系统"], ["zh-CN", "简体中文"], ["zh-TW", "繁體中文"],
    ["en", "English"], ["ja", "日本語"], ["ko", "한국어"],
    ["fr", "Français"], ["de", "Deutsch"], ["es", "Español"],
    ["ru", "Русский"], ["pt-BR", "Português (Brasil)"],
  ];
  const COPY = {
    "zh-CN": { commonSettings: "常用设置", language: "语言", followSystem: "跟随系统", displayProgress: "显示阅读进度", displayRating: "显示评分", displayTitle: "显示书名", animation: "动画", autoImport: "自动导入目录", semanticIndex: "语义索引", modelTags: "使用大模型分类的标签", modelAndTranslation: "大模型与翻译 API", singleClickOpen: "单击打开图书", dictionary: "词典", news: "资讯", settings: "设置", menu: "菜单", readingStats: "阅读统计", libraryQa: "书库问答", importBooks: "导入书籍", about: "关于", randomBook: "随机打开一本书", notes: "笔记汇总", libraryHealth: "书库体检", selectAll: "全选（批量删除）" },
    "zh-TW": { commonSettings: "常用設定", language: "語言", followSystem: "跟隨系統", displayProgress: "顯示閱讀進度", displayRating: "顯示評分", displayTitle: "顯示書名", animation: "動畫", autoImport: "自動匯入目錄", semanticIndex: "語意索引", modelTags: "使用大模型分類的標籤", modelAndTranslation: "大模型與翻譯 API", singleClickOpen: "單擊開啟圖書", dictionary: "詞典", news: "資訊", settings: "設定", menu: "選單", readingStats: "閱讀統計", libraryQa: "書庫問答", importBooks: "匯入書籍", about: "關於", randomBook: "隨機開啟一本書", notes: "筆記彙總", libraryHealth: "書庫健檢", selectAll: "全選（批量刪除）" },
    en: { commonSettings: "General settings", language: "Language", followSystem: "Follow system", displayProgress: "Show reading progress", displayRating: "Show rating", displayTitle: "Show title", animation: "Animation", autoImport: "Auto-import folders", semanticIndex: "Semantic index", modelTags: "Use AI classification tags", modelAndTranslation: "AI & translation API", singleClickOpen: "Open books with one click", dictionary: "Dictionary", news: "News", settings: "Settings", menu: "Menu", readingStats: "Reading statistics", libraryQa: "Library Q&A", importBooks: "Import books", about: "About", randomBook: "Open a random book", notes: "Notes", libraryHealth: "Library health", selectAll: "Select all (bulk delete)" },
    ja: { commonSettings: "一般設定", language: "言語", followSystem: "システムに従う", displayProgress: "読書進捗を表示", displayRating: "評価を表示", displayTitle: "書名を表示", animation: "アニメーション", autoImport: "フォルダーを自動取り込み", semanticIndex: "セマンティック索引", modelTags: "AI分類タグを使用", modelAndTranslation: "AI・翻訳 API", singleClickOpen: "ワンクリックで本を開く", dictionary: "辞書", news: "ニュース", settings: "設定", menu: "メニュー", readingStats: "読書統計", libraryQa: "ライブラリ Q&A", importBooks: "本をインポート", about: "情報", randomBook: "ランダムに本を開く", notes: "ノート", libraryHealth: "ライブラリ診断", selectAll: "すべて選択（削除）" },
    ko: { commonSettings: "일반 설정", language: "언어", followSystem: "시스템 따르기", displayProgress: "읽기 진행률 표시", displayRating: "평점 표시", displayTitle: "책 제목 표시", animation: "애니메이션", autoImport: "폴더 자동 가져오기", semanticIndex: "시맨틱 색인", modelTags: "AI 분류 태그 사용", modelAndTranslation: "AI 및 번역 API", singleClickOpen: "한 번 클릭해 책 열기", dictionary: "사전", news: "뉴스", settings: "설정", menu: "메뉴", readingStats: "독서 통계", libraryQa: "라이브러리 Q&A", importBooks: "책 가져오기", about: "정보", randomBook: "무작위 책 열기", notes: "노트", libraryHealth: "라이브러리 점검", selectAll: "모두 선택 (일괄 삭제)" },
    fr: { commonSettings: "Paramètres généraux", language: "Langue", followSystem: "Suivre le système", displayProgress: "Afficher la progression", displayRating: "Afficher la note", displayTitle: "Afficher le titre", animation: "Animations", autoImport: "Importer les dossiers automatiquement", semanticIndex: "Index sémantique", modelTags: "Utiliser les étiquettes IA", modelAndTranslation: "API IA et traduction", singleClickOpen: "Ouvrir les livres en un clic", dictionary: "Dictionnaire", news: "Actualités", settings: "Paramètres", menu: "Menu", readingStats: "Statistiques de lecture", libraryQa: "Questions-réponses", importBooks: "Importer des livres", about: "À propos", randomBook: "Ouvrir un livre au hasard", notes: "Notes", libraryHealth: "État de la bibliothèque", selectAll: "Tout sélectionner (suppression)" },
    de: { commonSettings: "Allgemeine Einstellungen", language: "Sprache", followSystem: "Systemsprache verwenden", displayProgress: "Lesefortschritt anzeigen", displayRating: "Bewertung anzeigen", displayTitle: "Buchtitel anzeigen", animation: "Animation", autoImport: "Ordner automatisch importieren", semanticIndex: "Semantischer Index", modelTags: "KI-Klassifizierungs-Tags verwenden", modelAndTranslation: "KI- und Übersetzungs-API", singleClickOpen: "Bücher mit einem Klick öffnen", dictionary: "Wörterbuch", news: "Nachrichten", settings: "Einstellungen", menu: "Menü", readingStats: "Lesestatistik", libraryQa: "Bibliotheksfragen", importBooks: "Bücher importieren", about: "Über", randomBook: "Zufälliges Buch öffnen", notes: "Notizen", libraryHealth: "Bibliotheksprüfung", selectAll: "Alles auswählen (löschen)" },
    es: { commonSettings: "Ajustes generales", language: "Idioma", followSystem: "Seguir al sistema", displayProgress: "Mostrar progreso de lectura", displayRating: "Mostrar valoración", displayTitle: "Mostrar título", animation: "Animación", autoImport: "Importar carpetas automáticamente", semanticIndex: "Índice semántico", modelTags: "Usar etiquetas de clasificación con IA", modelAndTranslation: "API de IA y traducción", singleClickOpen: "Abrir libros con un clic", dictionary: "Diccionario", news: "Noticias", settings: "Ajustes", menu: "Menú", readingStats: "Estadísticas de lectura", libraryQa: "Preguntas de biblioteca", importBooks: "Importar libros", about: "Acerca de", randomBook: "Abrir un libro al azar", notes: "Notas", libraryHealth: "Diagnóstico de biblioteca", selectAll: "Seleccionar todo (eliminar)" },
    ru: { commonSettings: "Общие настройки", language: "Язык", followSystem: "Как в системе", displayProgress: "Показывать прогресс", displayRating: "Показывать оценку", displayTitle: "Показывать название", animation: "Анимация", autoImport: "Автоимпорт папок", semanticIndex: "Семантический индекс", modelTags: "Использовать теги ИИ", modelAndTranslation: "ИИ и API перевода", singleClickOpen: "Открывать книги одним щелчком", dictionary: "Словарь", news: "Новости", settings: "Настройки", menu: "Меню", readingStats: "Статистика чтения", libraryQa: "Вопросы к библиотеке", importBooks: "Импортировать книги", about: "О программе", randomBook: "Открыть случайную книгу", notes: "Заметки", libraryHealth: "Проверка библиотеки", selectAll: "Выбрать все (удалить)" },
    "pt-BR": { commonSettings: "Configurações gerais", language: "Idioma", followSystem: "Seguir o sistema", displayProgress: "Mostrar progresso de leitura", displayRating: "Mostrar avaliação", displayTitle: "Mostrar título", animation: "Animação", autoImport: "Importar pastas automaticamente", semanticIndex: "Índice semântico", modelTags: "Usar etiquetas de classificação por IA", modelAndTranslation: "API de IA e tradução", singleClickOpen: "Abrir livros com um clique", dictionary: "Dicionário", news: "Notícias", settings: "Configurações", menu: "Menu", readingStats: "Estatísticas de leitura", libraryQa: "Perguntas da biblioteca", importBooks: "Importar livros", about: "Sobre", randomBook: "Abrir um livro aleatório", notes: "Notas", libraryHealth: "Saúde da biblioteca", selectAll: "Selecionar tudo (excluir)" },
  };
  Object.assign(COPY["zh-CN"], {
    newsTitle: "今日资讯", newsDescription: "按时间归并的轻量资讯流，只在你打开时加载。", backToShelf: "返回书架", manageSources: "管理来源", refresh: "刷新", sourceSettings: "资讯来源设置", sourceSettingsHint: "勾选想看的来源；设置只保存在此设备。", sourceSearch: "搜索来源、分类或关键词", restoreRecommended: "恢复推荐", doneAndRefresh: "完成并刷新", layout: "布局", listLayout: "横排布局", gridLayout: "方格布局", mixedOrder: "混合", bySourceOrder: "按来源", newsCategoryAll: "全部", newsSourceSummary: "显示 {count} 个来源", newsRecommendedSources: "使用推荐来源", newsSelectedSources: "已选 {count} / {max}", noMatchingSources: "没有找到匹配的内置来源。", maxSources: "最多选择 {max} 个来源。", chooseSource: "至少选择一个来源，或使用“恢复推荐”。", openWebPage: "打开网页 →", noNewsInCategory: "这个分类暂时没有资讯。", noNews: "暂无资讯。请刷新，或在“管理来源”中调整显示内容。", loadingNews: "加载中…", refreshingNews: "刷新中…", newsUpdatedAt: "更新于 {time}", libraryDescription: "先在本机语义索引中检索，再只把命中的少量段落发送到你已配置的智读服务。每条回答都可跳回原书章节。", bookClassification: "书籍分类", questionHistory: "问答记录", localSearchCitations: "本地检索 · 可追溯引文", searchScope: "检索范围", libraryQuestion: "书库问答", crossBookCompare: "跨书对比", yourQuestion: "你的问题", startQuestion: "开始问答", answerPlaceholder: "选择范围并输入问题后开始。若没有结果，请先在主窗口的设置中建立语义索引。", questionPlaceholder: "例如：这些书如何解释清末财政困境？\n跨书对比时：比较选中作品对同一主题的观点与依据。", allTags: "全部标签", allCollections: "全部收藏夹", clearFilters: "清除筛选", cancelLimit: "取消限定", clearSelection: "清空选择", selectVisible: "全选当前列表", invertVisible: "反选当前列表", noBooks: "书架中还没有图书。", noFilteredBooks: "没有符合当前标签和收藏夹的图书。", unnamedQuestion: "未命名问答", noQuestionHistory: "还没有保存的书库问答。完成一次问答后会自动保存到这里。", loadingLibrary: "正在读取书架与智读配置…", askInProgress: "检索并问答中…", enterQuestion: "请输入问题。", libraryQuestionFailed: "书库问答失败。", libraryHistory: "问答记录", returnToAnswer: "返回本次回答", delete: "删除", copy: "复制", cut: "剪切", paste: "粘贴"
  });
  Object.assign(COPY["zh-TW"], {
    newsTitle: "今日資訊", newsDescription: "依時間彙整的輕量資訊流，只在你開啟時載入。", backToShelf: "返回書架", manageSources: "管理來源", refresh: "重新整理", sourceSettings: "資訊來源設定", sourceSettingsHint: "勾選想看的來源；設定只儲存在此裝置。", sourceSearch: "搜尋來源、分類或關鍵字", restoreRecommended: "恢復推薦", doneAndRefresh: "完成並重新整理", layout: "版面", listLayout: "橫排版面", gridLayout: "方格版面", mixedOrder: "混合", bySourceOrder: "依來源", newsCategoryAll: "全部", newsSourceSummary: "顯示 {count} 個來源", newsRecommendedSources: "使用推薦來源", newsSelectedSources: "已選 {count} / {max}", noMatchingSources: "沒有找到相符的內建來源。", maxSources: "最多選擇 {max} 個來源。", openWebPage: "開啟網頁 →", noNewsInCategory: "這個分類暫時沒有資訊。", noNews: "暫無資訊。請重新整理，或在「管理來源」中調整顯示內容。", loadingNews: "載入中…", refreshingNews: "重新整理中…", newsUpdatedAt: "更新於 {time}", libraryDescription: "先在本機語意索引中檢索，再只把命中的少量段落傳送到你已設定的智讀服務。每則回答都可跳回原書章節。", bookClassification: "書籍分類", questionHistory: "問答記錄", localSearchCitations: "本機檢索 · 可追溯引文", searchScope: "檢索範圍", libraryQuestion: "書庫問答", crossBookCompare: "跨書比較", yourQuestion: "你的問題", startQuestion: "開始問答", answerPlaceholder: "選擇範圍並輸入問題後開始。若沒有結果，請先在主視窗的設定中建立語意索引。", questionPlaceholder: "例如：這些書如何解釋清末財政困境？\n跨書比較時：比較選中作品對同一主題的觀點與依據。", allTags: "全部標籤", allCollections: "全部收藏夾", clearFilters: "清除篩選", cancelLimit: "取消限定", clearSelection: "清空選擇", selectVisible: "全選目前列表", invertVisible: "反選目前列表", loadingLibrary: "正在讀取書架與智讀設定…", askInProgress: "檢索並問答中…", enterQuestion: "請輸入問題。", libraryQuestionFailed: "書庫問答失敗。", libraryHistory: "問答記錄", returnToAnswer: "返回本次回答", delete: "刪除", copy: "複製", cut: "剪下", paste: "貼上"
  });
  Object.assign(COPY.en, {
    newsTitle: "Today’s news", newsDescription: "A lightweight, time-ordered news feed that loads only when you open it.", backToShelf: "Back to shelf", manageSources: "Manage sources", refresh: "Refresh", sourceSettings: "News sources", sourceSettingsHint: "Choose the sources you want. This setting is stored on this device only.", sourceSearch: "Search sources, categories, or keywords", restoreRecommended: "Restore recommended", doneAndRefresh: "Done and refresh", layout: "Layout", listLayout: "List layout", gridLayout: "Grid layout", mixedOrder: "Mixed", bySourceOrder: "By source", newsCategoryAll: "All", newsSourceSummary: "Showing {count} sources", newsRecommendedSources: "Using recommended sources", newsSelectedSources: "Selected {count} / {max}", noMatchingSources: "No matching built-in sources.", maxSources: "You can select up to {max} sources.", chooseSource: "Select at least one source, or restore the recommended set.", openWebPage: "Open webpage →", noNewsInCategory: "No news in this category yet.", noNews: "No news yet. Refresh, or change the sources in Manage sources.", loadingNews: "Loading…", refreshingNews: "Refreshing…", newsUpdatedAt: "Updated {time}", libraryDescription: "Search the local semantic index first, then send only a few matched passages to your configured AI reading service. Every answer can return to the original chapter.", bookClassification: "Book classification", questionHistory: "Question history", localSearchCitations: "Local search · traceable citations", searchScope: "Search scope", libraryQuestion: "Library Q&A", crossBookCompare: "Cross-book comparison", yourQuestion: "Your question", startQuestion: "Ask", answerPlaceholder: "Choose a scope and enter a question. If there are no results, build a semantic index in the main settings first.", questionPlaceholder: "For example: How do these books explain the late Qing fiscal crisis?\nFor comparison: compare the selected works’ views and evidence on one topic.", allTags: "All tags", allCollections: "All collections", clearFilters: "Clear filters", cancelLimit: "Remove limit", clearSelection: "Clear selection", selectVisible: "Select visible", invertVisible: "Invert visible", noBooks: "There are no books on the shelf.", noFilteredBooks: "No books match the current tags and collections.", unnamedQuestion: "Untitled question", noQuestionHistory: "There is no saved Library Q&A yet. Questions are saved automatically after a successful answer.", loadingLibrary: "Loading shelf and AI-reading settings…", askInProgress: "Searching and answering…", enterQuestion: "Enter a question.", libraryQuestionFailed: "Library Q&A failed.", libraryHistory: "Question history", returnToAnswer: "Return to current answer", delete: "Delete", copy: "Copy", cut: "Cut", paste: "Paste"
  });
  function selectedLanguage() { return localStorage.getItem(STORAGE_KEY) || "system"; }
  function resolvedLanguage() {
    const selected = selectedLanguage();
    if (selected !== "system") return selected;
    const system = String(navigator.language || "zh-CN").toLowerCase();
    if (system.startsWith("zh-tw") || system.startsWith("zh-hk") || system.startsWith("zh-mo")) return "zh-TW";
    const exact = LANGUAGES.map((item) => item[0]).find((item) => item.toLowerCase() === system);
    return exact || (system.split("-")[0] === "zh" ? "zh-CN" : system.split("-")[0]);
  }
  function t(key) { return (COPY[resolvedLanguage()] || COPY.en)[key] || COPY.en[key] || COPY["zh-CN"][key] || key; }
  function apply(root) {
    const language = resolvedLanguage();
    document.documentElement.lang = language;
    (root || document).querySelectorAll?.("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
    (root || document).querySelectorAll?.("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
    (root || document).querySelectorAll?.("[data-i18n-title]").forEach((element) => { element.title = t(element.dataset.i18nTitle); });
    (root || document).querySelectorAll?.("[data-i18n-aria]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAria)); });
  }
  function populate(select) {
    if (!select) return;
    select.replaceChildren(...LANGUAGES.map(([value, label]) => {
      const option = document.createElement("option"); option.value = value; option.textContent = value === "system" ? t("followSystem") : label; return option;
    }));
    select.value = selectedLanguage();
  }
  function setLanguage(value) {
    localStorage.setItem(STORAGE_KEY, LANGUAGES.some(([id]) => id === value) ? value : "system");
    apply(document);
    document.querySelectorAll(".app-language-select").forEach(populate);
    global.dispatchEvent(new CustomEvent("app-language-changed", { detail: { selected: selectedLanguage(), resolved: resolvedLanguage() } }));
  }
  global.ReaderAppI18n = { STORAGE_KEY, apply, populate, selectedLanguage, resolvedLanguage, setLanguage, t };
  document.addEventListener("DOMContentLoaded", () => apply(document), { once: true });
})(window);
