// 主窗口本地化的单一入口。新增界面只需加 data-i18n，不把语言选择变成
// 只有下拉框、没有实际界面变化的假设置。
(function (global) {
  const STORAGE_KEY = "appLanguageV1";
  const LANGUAGES = [
    ["system", "跟随系统"], ["zh-CN", "简体中文"], ["zh-TW", "繁體中文"],
    ["en", "English"], ["ja", "日本語"], ["ko", "한국어"],
    ["fr", "Français"], ["de", "Deutsch"], ["es", "Español"],
    ["ru", "Русский"], ["pt-BR", "Português (Brasil)"],
  ];
  const COPY = {
    "zh-CN": { commonSettings: "常用设置", language: "语言", followSystem: "跟随系统", displayProgress: "显示阅读进度", displayRating: "显示评分", displayTitle: "显示书名", animation: "动画", autoImport: "自动导入目录", semanticIndex: "语义索引", modelTags: "使用大模型分类的标签", modelAndTranslation: "大模型与翻译 API", singleClickOpen: "单击打开图书", dictionary: "词典", news: "资讯", settings: "设置", menu: "菜单", readingStats: "阅读统计", libraryQa: "书库问答", importBooks: "导入书籍", about: "关于", randomBook: "随机打开一本书", notes: "笔记汇总", libraryHealth: "书库体检", selectAll: "全选（批量删除）" },
    "zh-TW": { commonSettings: "常用設定", language: "語言", followSystem: "跟隨系統", displayProgress: "顯示閱讀進度", displayRating: "顯示評分", displayTitle: "顯示書名", animation: "動畫", autoImport: "自動匯入目錄", semanticIndex: "語意索引", modelTags: "使用大模型分類的標籤", modelAndTranslation: "大模型與翻譯 API", singleClickOpen: "單擊開啟圖書", dictionary: "詞典", news: "資訊", settings: "設定", menu: "選單", readingStats: "閱讀統計", libraryQa: "書庫問答", importBooks: "匯入書籍", about: "關於", randomBook: "隨機開啟一本書", notes: "筆記彙總", libraryHealth: "書庫健檢", selectAll: "全選（批量刪除）" },
    en: { commonSettings: "General settings", language: "Language", followSystem: "Follow system", displayProgress: "Show reading progress", displayRating: "Show rating", displayTitle: "Show title", animation: "Animation", autoImport: "Auto-import folders", semanticIndex: "Semantic index", modelTags: "Use AI classification tags", modelAndTranslation: "AI & translation API", singleClickOpen: "Open books with one click", dictionary: "Dictionary", news: "News", settings: "Settings", menu: "Menu", readingStats: "Reading statistics", libraryQa: "Library Q&A", importBooks: "Import books", about: "About", randomBook: "Open a random book", notes: "Notes", libraryHealth: "Library health", selectAll: "Select all (bulk delete)" },
    ja: { commonSettings: "一般設定", language: "言語", followSystem: "システムに従う", displayProgress: "読書進捗を表示", displayRating: "評価を表示", displayTitle: "書名を表示", animation: "アニメーション", autoImport: "フォルダーを自動取り込み", semanticIndex: "セマンティック索引", modelTags: "AI分類タグを使用", modelAndTranslation: "AI・翻訳 API", singleClickOpen: "ワンクリックで本を開く", dictionary: "辞書", news: "ニュース", settings: "設定", menu: "メニュー", readingStats: "読書統計", libraryQa: "ライブラリ Q&A", importBooks: "本をインポート", about: "情報", randomBook: "ランダムに本を開く", notes: "ノート", libraryHealth: "ライブラリ診断", selectAll: "すべて選択（削除）" },
    ko: { commonSettings: "일반 설정", language: "언어", followSystem: "시스템 따르기", displayProgress: "읽기 진행률 표시", displayRating: "평점 표시", displayTitle: "책 제목 표시", animation: "애니메이션", autoImport: "폴더 자동 가져오기", semanticIndex: "시맨틱 색인", modelTags: "AI 분류 태그 사용", modelAndTranslation: "AI 및 번역 API", singleClickOpen: "한 번 클릭해 책 열기", dictionary: "사전", news: "뉴스", settings: "설정", menu: "메뉴", readingStats: "독서 통계", libraryQa: "라이브러리 Q&A", importBooks: "책 가져오기", about: "정보", randomBook: "무작위 책 열기", notes: "노트", libraryHealth: "라이브러리 점검", selectAll: "모두 선택 (일괄 삭제)" },
    fr: { commonSettings: "Paramètres généraux", language: "Langue", followSystem: "Suivre le système", displayProgress: "Afficher la progression", displayRating: "Afficher la note", displayTitle: "Afficher le titre", animation: "Animations", autoImport: "Importer les dossiers automatiquement", semanticIndex: "Index sémantique", modelTags: "Utiliser les étiquettes IA", modelAndTranslation: "API IA et traduction", singleClickOpen: "Ouvrir les livres en un clic", dictionary: "Dictionnaire", news: "Actualités", settings: "Paramètres", menu: "Menu", readingStats: "Statistiques de lecture", libraryQa: "Questions-réponses", importBooks: "Importer des livres", about: "À propos", randomBook: "Ouvrir un livre au hasard", notes: "Notes", libraryHealth: "État de la bibliothèque", selectAll: "Tout sélectionner (suppression)" },
    de: { commonSettings: "Allgemeine Einstellungen", language: "Sprache", followSystem: "Systemsprache verwenden", displayProgress: "Lesefortschritt anzeigen", displayRating: "Bewertung anzeigen", displayTitle: "Buchtitel anzeigen", animation: "Animation", autoImport: "Ordner automatisch importieren", semanticIndex: "Semantischer Index", modelTags: "KI-Klassifizierungs-Tags verwenden", modelAndTranslation: "KI- und Übersetzungs-API", singleClickOpen: "Bücher mit einem Klick öffnen", dictionary: "Wörterbuch", news: "Nachrichten", settings: "Einstellungen", menu: "Menü", readingStats: "Lesestatistik", libraryQa: "Bibliotheksfragen", importBooks: "Bücher importieren", about: "Über", randomBook: "Zufälliges Buch öffnen", notes: "Notizen", libraryHealth: "Bibliotheksprüfung", selectAll: "Alles auswählen (löschen)" },
    es: { commonSettings: "Ajustes generales", language: "Idioma", followSystem: "Seguir al sistema", displayProgress: "Mostrar progreso de lectura", displayRating: "Mostrar valoración", displayTitle: "Mostrar título", animation: "Animación", autoImport: "Importar carpetas automáticamente", semanticIndex: "Índice semántico", modelTags: "Usar etiquetas de clasificación con IA", modelAndTranslation: "API de IA y traducción", singleClickOpen: "Abrir libros con un clic", dictionary: "Diccionario", news: "Noticias", settings: "Ajustes", menu: "Menú", readingStats: "Estadísticas de lectura", libraryQa: "Preguntas de biblioteca", importBooks: "Importar libros", about: "Acerca de", randomBook: "Abrir un libro al azar", notes: "Notas", libraryHealth: "Diagnóstico de biblioteca", selectAll: "Seleccionar todo (eliminar)" },
    ru: { commonSettings: "Общие настройки", language: "Язык", followSystem: "Как в системе", displayProgress: "Показывать прогресс", displayRating: "Показывать оценку", displayTitle: "Показывать название", animation: "Анимация", autoImport: "Автоимпорт папок", semanticIndex: "Семантический индекс", modelTags: "Использовать теги ИИ", modelAndTranslation: "ИИ и API перевода", singleClickOpen: "Открывать книги одним щелчком", dictionary: "Словарь", news: "Новости", settings: "Настройки", menu: "Меню", readingStats: "Статистика чтения", libraryQa: "Вопросы к библиотеке", importBooks: "Импортировать книги", about: "О программе", randomBook: "Открыть случайную книгу", notes: "Заметки", libraryHealth: "Проверка библиотеки", selectAll: "Выбрать все (удалить)" },
    "pt-BR": { commonSettings: "Configurações gerais", language: "Idioma", followSystem: "Seguir o sistema", displayProgress: "Mostrar progresso de leitura", displayRating: "Mostrar avaliação", displayTitle: "Mostrar título", animation: "Animação", autoImport: "Importar pastas automaticamente", semanticIndex: "Índice semântico", modelTags: "Usar etiquetas de classificação por IA", modelAndTranslation: "API de IA e tradução", singleClickOpen: "Abrir livros com um clique", dictionary: "Dicionário", news: "Notícias", settings: "Configurações", menu: "Menu", readingStats: "Estatísticas de leitura", libraryQa: "Perguntas da biblioteca", importBooks: "Importar livros", about: "Sobre", randomBook: "Abrir um livro aleatório", notes: "Notas", libraryHealth: "Saúde da biblioteca", selectAll: "Selecionar tudo (excluir)" },
  };
  Object.assign(COPY["zh-CN"], {
    newsTitle: "今日资讯", newsDescription: "按时间归并的轻量资讯流，只在你打开时加载。", backToShelf: "返回书架", manageSources: "管理来源", refresh: "刷新", sourceSettings: "资讯来源设置", sourceSettingsHint: "勾选想看的来源；设置只保存在此设备。", sourceSearch: "搜索来源、分类或关键词", restoreRecommended: "恢复推荐", doneAndRefresh: "完成并刷新", layout: "布局", listLayout: "横排布局", gridLayout: "方格布局", mixedOrder: "混合", bySourceOrder: "按来源", newsCategoryAll: "全部", newsSourceSummary: "显示 {count} 个来源", newsRecommendedSources: "使用推荐来源", newsSelectedSources: "已选 {count} / {max}", noMatchingSources: "没有找到匹配的内置来源。", maxSources: "最多选择 {max} 个来源。", chooseSource: "至少选择一个来源，或使用“恢复推荐”。", openWebPage: "打开网页 →", noNewsInCategory: "这个分类暂时没有资讯。", noNews: "暂无资讯。请刷新，或在“管理来源”中调整显示内容。", loadingNews: "加载中…", refreshingNews: "刷新中…", newsUpdatedAt: "更新于 {time}", libraryDescription: "先在本机语义索引中检索，再只把命中的少量段落发送到你已配置的智读服务。每条回答都可跳回原书章节。", bookClassification: "书籍分类", questionHistory: "问答记录", localSearchCitations: "本地检索 · 可追溯引文", searchScope: "检索范围", libraryQuestion: "书库问答", crossBookCompare: "跨书对比", yourQuestion: "你的问题", startQuestion: "开始问答", answerPlaceholder: "选择范围并输入问题后开始。若没有结果，请先在主窗口的设置中建立语义索引。", questionPlaceholder: "例如：这些书如何解释清末财政困境？\n跨书对比时：比较选中作品对同一主题的观点与依据。", allTags: "全部标签", allCollections: "全部收藏夹", clearFilters: "清除筛选", cancelLimit: "取消限定", clearSelection: "清空选择", selectVisible: "全选当前列表", invertVisible: "反选当前列表", noBooks: "书架中还没有图书。", noFilteredBooks: "没有符合当前标签和收藏夹的图书。", unnamedQuestion: "未命名问答", noQuestionHistory: "还没有保存的书库问答。完成一次问答后会自动保存到这里。", loadingLibrary: "正在读取书架与智读配置…", askInProgress: "检索并问答中…", enterQuestion: "请输入问题。", libraryQuestionFailed: "书库问答失败。", libraryHistory: "问答记录", returnToAnswer: "返回本次回答", delete: "删除", copy: "复制", cut: "剪切", paste: "粘贴"
  });
  Object.assign(COPY["zh-TW"], {
    newsTitle: "今日資訊", newsDescription: "依時間彙整的輕量資訊流，只在你開啟時載入。", backToShelf: "返回書架", manageSources: "管理來源", refresh: "重新整理", sourceSettings: "資訊來源設定", sourceSettingsHint: "勾選想看的來源；設定只儲存在此裝置。", sourceSearch: "搜尋來源、分類或關鍵字", restoreRecommended: "恢復推薦", doneAndRefresh: "完成並重新整理", layout: "版面", listLayout: "橫排版面", gridLayout: "方格版面", mixedOrder: "混合", bySourceOrder: "依來源", newsCategoryAll: "全部", newsSourceSummary: "顯示 {count} 個來源", newsRecommendedSources: "使用推薦來源", newsSelectedSources: "已選 {count} / {max}", noMatchingSources: "沒有找到相符的內建來源。", maxSources: "最多選擇 {max} 個來源。", openWebPage: "開啟網頁 →", noNewsInCategory: "這個分類暫時沒有資訊。", noNews: "暫無資訊。請重新整理，或在「管理來源」中調整顯示內容。", loadingNews: "載入中…", refreshingNews: "重新整理中…", newsUpdatedAt: "更新於 {time}", libraryDescription: "先在本機語意索引中檢索，再只把命中的少量段落傳送到你已設定的智讀服務。每則回答都可跳回原書章節。", bookClassification: "書籍分類", questionHistory: "問答記錄", localSearchCitations: "本機檢索 · 可追溯引文", searchScope: "檢索範圍", libraryQuestion: "書庫問答", crossBookCompare: "跨書比較", yourQuestion: "你的問題", startQuestion: "開始問答", answerPlaceholder: "選擇範圍並輸入問題後開始。若沒有結果，請先在主視窗的設定中建立語意索引。", questionPlaceholder: "例如：這些書如何解釋清末財政困境？\n跨書比較時：比較選中作品對同一主題的觀點與依據。", allTags: "全部標籤", allCollections: "全部收藏夾", clearFilters: "清除篩選", cancelLimit: "取消限定", clearSelection: "清空選擇", selectVisible: "全選目前列表", invertVisible: "反選目前列表", loadingLibrary: "正在讀取書架與智讀設定…", askInProgress: "檢索並問答中…", enterQuestion: "請輸入問題。", libraryQuestionFailed: "書庫問答失敗。", libraryHistory: "問答記錄", returnToAnswer: "返回本次回答", delete: "刪除", copy: "複製", cut: "剪下", paste: "貼上"
  });
  Object.assign(COPY.en, {
    newsTitle: "Today’s news", newsDescription: "A lightweight, time-ordered news feed that loads only when you open it.", backToShelf: "Back to shelf", manageSources: "Manage sources", refresh: "Refresh", sourceSettings: "News sources", sourceSettingsHint: "Choose the sources you want. This setting is stored on this device only.", sourceSearch: "Search sources, categories, or keywords", restoreRecommended: "Restore recommended", doneAndRefresh: "Done and refresh", layout: "Layout", listLayout: "List layout", gridLayout: "Grid layout", mixedOrder: "Mixed", bySourceOrder: "By source", newsCategoryAll: "All", newsSourceSummary: "Showing {count} sources", newsRecommendedSources: "Using recommended sources", newsSelectedSources: "Selected {count} / {max}", noMatchingSources: "No matching built-in sources.", maxSources: "You can select up to {max} sources.", chooseSource: "Select at least one source, or restore the recommended set.", openWebPage: "Open webpage →", noNewsInCategory: "No news in this category yet.", noNews: "No news yet. Refresh, or change the sources in Manage sources.", loadingNews: "Loading…", refreshingNews: "Refreshing…", newsUpdatedAt: "Updated {time}", libraryDescription: "Search the local semantic index first, then send only a few matched passages to your configured AI reading service. Every answer can return to the original chapter.", bookClassification: "Book classification", questionHistory: "Question history", localSearchCitations: "Local search · traceable citations", searchScope: "Search scope", libraryQuestion: "Library Q&A", crossBookCompare: "Cross-book comparison", yourQuestion: "Your question", startQuestion: "Ask", answerPlaceholder: "Choose a scope and enter a question. If there are no results, build a semantic index in the main settings first.", questionPlaceholder: "For example: How do these books explain the late Qing fiscal crisis?\nFor comparison: compare the selected works’ views and evidence on one topic.", allTags: "All tags", allCollections: "All collections", clearFilters: "Clear filters", cancelLimit: "Remove limit", clearSelection: "Clear selection", selectVisible: "Select visible", invertVisible: "Invert visible", noBooks: "There are no books on the shelf.", noFilteredBooks: "No books match the current tags and collections.", unnamedQuestion: "Untitled question", noQuestionHistory: "There is no saved Library Q&A yet. Questions are saved automatically after a successful answer.", loadingLibrary: "Loading shelf and AI-reading settings…", askInProgress: "Searching and answering…", enterQuestion: "Enter a question.", libraryQuestionFailed: "Library Q&A failed.", libraryHistory: "Question history", returnToAnswer: "Return to current answer", delete: "Delete", copy: "Copy", cut: "Cut", paste: "Paste"
  });
  const SETTINGS_COPY = {
    "zh-CN": { defaultOpenTitle: "默认打开方式", defaultOpenDescription: "安装版支持将 EPUB 和 PDF 设为由鲲鹏阅读器打开；请在系统的“按文件类型选择默认值”中分别设置。", defaultOpenButton: "设置 EPUB / PDF 默认应用", recoveryTitle: "数据恢复点", recoveryLoading: "正在读取恢复点状态…", recoveryCreate: "立即创建", recoveryCreating: "正在创建…", recoverySelected: "恢复选中恢复点", recoveryRestoring: "正在恢复…", recoveryStatus: "已保留 {count} 个恢复点，共 {size}；最近一次 {latest}。每日自动创建，最多保留 7 个。", recoveryEmpty: "尚无恢复点；软件会每日自动创建，最多保留 7 个。", recoveryOption: "恢复点 {created}（{size}）", recoverySelect: "选择数据恢复点", dataExport: "⬆ 导出数据包", dataImport: "⬇ 导入数据包", recoveryReadFailed: "恢复点状态读取失败：{error}" },
    "zh-TW": { defaultOpenTitle: "預設開啟方式", defaultOpenDescription: "安裝版支援將 EPUB 和 PDF 設為由鯤鵬閱讀器開啟；請在系統的「依檔案類型選擇預設值」中分別設定。", defaultOpenButton: "設定 EPUB / PDF 預設應用程式", recoveryTitle: "資料恢復點", recoveryLoading: "正在讀取恢復點狀態…", recoveryCreate: "立即建立", recoveryCreating: "正在建立…", recoverySelected: "恢復選取的恢復點", recoveryRestoring: "正在恢復…", recoveryStatus: "已保留 {count} 個恢復點，共 {size}；最近一次 {latest}。每日自動建立，最多保留 7 個。", recoveryEmpty: "尚無恢復點；軟體會每日自動建立，最多保留 7 個。", recoveryOption: "恢復點 {created}（{size}）", recoverySelect: "選擇資料恢復點", dataExport: "⬆ 匯出資料包", dataImport: "⬇ 匯入資料包", recoveryReadFailed: "讀取恢復點狀態失敗：{error}" },
    en: { defaultOpenTitle: "Default apps", defaultOpenDescription: "The installed app can open EPUB and PDF files. Set it for each type in Windows Default apps by file type.", defaultOpenButton: "Set EPUB / PDF defaults", recoveryTitle: "Recovery points", recoveryLoading: "Loading recovery-point status…", recoveryCreate: "Create now", recoveryCreating: "Creating…", recoverySelected: "Restore selected point", recoveryRestoring: "Restoring…", recoveryStatus: "{count} recovery points retained ({size}); latest: {latest}. One is created daily, with up to 7 retained.", recoveryEmpty: "No recovery points yet. The app creates one daily and retains up to 7.", recoveryOption: "Recovery point {created} ({size})", recoverySelect: "Choose a recovery point", dataExport: "⬆ Export data package", dataImport: "⬇ Import data package", recoveryReadFailed: "Could not read recovery-point status: {error}" },
    ja: { defaultOpenTitle: "既定の開き方", defaultOpenDescription: "インストール版では EPUB と PDF を鯤鵬閲覧器で開けます。Windows のファイルの種類ごとの既定のアプリで、それぞれ設定してください。", defaultOpenButton: "EPUB / PDF の既定アプリを設定", recoveryTitle: "復元ポイント", recoveryLoading: "復元ポイントの状態を読み込んでいます…", recoveryCreate: "今すぐ作成", recoveryCreating: "作成中…", recoverySelected: "選択したポイントを復元", recoveryRestoring: "復元中…", recoveryStatus: "{count} 個の復元ポイントを保持中（{size}）。最新: {latest}。毎日自動作成され、最大 7 個を保持します。", recoveryEmpty: "復元ポイントはありません。毎日自動作成され、最大 7 個を保持します。", recoveryOption: "復元ポイント {created}（{size}）", recoverySelect: "復元ポイントを選択", dataExport: "⬆ データパッケージをエクスポート", dataImport: "⬇ データパッケージをインポート", recoveryReadFailed: "復元ポイントの状態を読み込めませんでした: {error}" },
    ko: { defaultOpenTitle: "기본 열기 방식", defaultOpenDescription: "설치 버전에서는 EPUB과 PDF를 쿤펑 리더로 열 수 있습니다. Windows의 파일 형식별 기본 앱에서 각각 설정하세요.", defaultOpenButton: "EPUB / PDF 기본 앱 설정", recoveryTitle: "복구 지점", recoveryLoading: "복구 지점 상태를 불러오는 중…", recoveryCreate: "지금 만들기", recoveryCreating: "만드는 중…", recoverySelected: "선택한 지점 복원", recoveryRestoring: "복원 중…", recoveryStatus: "복구 지점 {count}개를 보관 중({size}), 최근: {latest}. 매일 자동으로 만들며 최대 7개를 보관합니다.", recoveryEmpty: "복구 지점이 없습니다. 매일 자동으로 만들며 최대 7개를 보관합니다.", recoveryOption: "복구 지점 {created}({size})", recoverySelect: "복구 지점 선택", dataExport: "⬆ 데이터 패키지 내보내기", dataImport: "⬇ 데이터 패키지 가져오기", recoveryReadFailed: "복구 지점 상태를 읽지 못했습니다: {error}" },
    fr: { defaultOpenTitle: "Applications par défaut", defaultOpenDescription: "La version installée peut ouvrir les fichiers EPUB et PDF. Configurez-les dans les applications par défaut de Windows, par type de fichier.", defaultOpenButton: "Définir les valeurs EPUB / PDF", recoveryTitle: "Points de récupération", recoveryLoading: "Chargement de l’état des points de récupération…", recoveryCreate: "Créer maintenant", recoveryCreating: "Création…", recoverySelected: "Restaurer le point sélectionné", recoveryRestoring: "Restauration…", recoveryStatus: "{count} points de récupération conservés ({size}) ; dernier : {latest}. Un point est créé chaque jour, jusqu’à 7 conservés.", recoveryEmpty: "Aucun point de récupération. L’application en crée un chaque jour et en conserve jusqu’à 7.", recoveryOption: "Point de récupération {created} ({size})", recoverySelect: "Choisir un point de récupération", dataExport: "⬆ Exporter le paquet de données", dataImport: "⬇ Importer le paquet de données", recoveryReadFailed: "Impossible de lire l’état des points de récupération : {error}" },
    de: { defaultOpenTitle: "Standard-Apps", defaultOpenDescription: "Die installierte App kann EPUB- und PDF-Dateien öffnen. Legen Sie sie in den Windows-Standard-Apps nach Dateityp fest.", defaultOpenButton: "EPUB / PDF als Standard festlegen", recoveryTitle: "Wiederherstellungspunkte", recoveryLoading: "Wiederherstellungspunkte werden geladen…", recoveryCreate: "Jetzt erstellen", recoveryCreating: "Wird erstellt…", recoverySelected: "Ausgewählten Punkt wiederherstellen", recoveryRestoring: "Wird wiederhergestellt…", recoveryStatus: "{count} Wiederherstellungspunkte ({size}) gespeichert; letzter: {latest}. Täglich wird einer erstellt, maximal 7 werden behalten.", recoveryEmpty: "Noch keine Wiederherstellungspunkte. Die App erstellt täglich einen und behält maximal 7.", recoveryOption: "Wiederherstellungspunkt {created} ({size})", recoverySelect: "Wiederherstellungspunkt auswählen", dataExport: "⬆ Datenpaket exportieren", dataImport: "⬇ Datenpaket importieren", recoveryReadFailed: "Status der Wiederherstellungspunkte konnte nicht gelesen werden: {error}" },
    es: { defaultOpenTitle: "Aplicaciones predeterminadas", defaultOpenDescription: "La aplicación instalada puede abrir archivos EPUB y PDF. Configúrela en las aplicaciones predeterminadas de Windows por tipo de archivo.", defaultOpenButton: "Configurar EPUB / PDF predeterminados", recoveryTitle: "Puntos de recuperación", recoveryLoading: "Cargando el estado de los puntos de recuperación…", recoveryCreate: "Crear ahora", recoveryCreating: "Creando…", recoverySelected: "Restaurar el punto seleccionado", recoveryRestoring: "Restaurando…", recoveryStatus: "Se conservan {count} puntos de recuperación ({size}); último: {latest}. Se crea uno cada día, hasta un máximo de 7.", recoveryEmpty: "Aún no hay puntos de recuperación. La aplicación crea uno al día y conserva hasta 7.", recoveryOption: "Punto de recuperación {created} ({size})", recoverySelect: "Elegir un punto de recuperación", dataExport: "⬆ Exportar paquete de datos", dataImport: "⬇ Importar paquete de datos", recoveryReadFailed: "No se pudo leer el estado de los puntos de recuperación: {error}" },
    ru: { defaultOpenTitle: "Приложения по умолчанию", defaultOpenDescription: "Установленная версия может открывать EPUB и PDF. Настройте её в параметрах Windows по типу файлов.", defaultOpenButton: "Настроить EPUB / PDF по умолчанию", recoveryTitle: "Точки восстановления", recoveryLoading: "Загрузка состояния точек восстановления…", recoveryCreate: "Создать сейчас", recoveryCreating: "Создание…", recoverySelected: "Восстановить выбранную точку", recoveryRestoring: "Восстановление…", recoveryStatus: "Сохранено точек восстановления: {count} ({size}); последняя: {latest}. Одна создаётся ежедневно, хранится не более 7.", recoveryEmpty: "Точек восстановления пока нет. Приложение создаёт одну ежедневно и хранит не более 7.", recoveryOption: "Точка восстановления {created} ({size})", recoverySelect: "Выбрать точку восстановления", dataExport: "⬆ Экспортировать пакет данных", dataImport: "⬇ Импортировать пакет данных", recoveryReadFailed: "Не удалось прочитать состояние точек восстановления: {error}" },
    "pt-BR": { defaultOpenTitle: "Aplicativos padrão", defaultOpenDescription: "A versão instalada pode abrir arquivos EPUB e PDF. Defina-a nos Aplicativos padrão do Windows por tipo de arquivo.", defaultOpenButton: "Definir padrões EPUB / PDF", recoveryTitle: "Pontos de recuperação", recoveryLoading: "Carregando o estado dos pontos de recuperação…", recoveryCreate: "Criar agora", recoveryCreating: "Criando…", recoverySelected: "Restaurar ponto selecionado", recoveryRestoring: "Restaurando…", recoveryStatus: "{count} pontos de recuperação mantidos ({size}); mais recente: {latest}. Um é criado diariamente, com até 7 mantidos.", recoveryEmpty: "Ainda não há pontos de recuperação. O aplicativo cria um por dia e mantém até 7.", recoveryOption: "Ponto de recuperação {created} ({size})", recoverySelect: "Escolher ponto de recuperação", dataExport: "⬆ Exportar pacote de dados", dataImport: "⬇ Importar pacote de dados", recoveryReadFailed: "Não foi possível ler o estado dos pontos de recuperação: {error}" }
  };
  Object.entries(SETTINGS_COPY).forEach(([locale, copy]) => Object.assign(COPY[locale], copy));
  const ACCOUNT_SEARCH_COPY = {
    "zh-CN": { syncTitle: "同步", accountLabel: "账号", password: "密码", register: "注册", login: "登录", recoverPassword: "找回密码", boundEmail: "已绑定的邮箱", emailCode: "邮箱验证码", newLoginPassword: "新登录密码（至少 8 个字符）", resetAndLogin: "确认重置并登录", accountPrefix: "账号：", syncNow: "同步", accountSecurity: "账户安全", logout: "退出登录", syncContent: "同步内容", syncProgress: "阅读进度与续读位置", syncReadingData: "书签、高亮、批注、评分、标签与收藏夹", syncVocabulary: "生词本", syncStatistics: "阅读统计", syncTags: "大模型书籍分类标签", syncApi: "大模型与翻译 API 配置（不含密钥）", syncHistory: "智读与书库问答记录（可选）", syncSecrets: "加密 API Key 与翻译密钥（可选）", smartReading: "智读、书库问答与翻译", smartReadingHelp: "分类标签和配置默认同步；问答记录与加密密钥可在同步设置中开启。", syncSettings: "同步设置", lastSync: "最近同步：{time}", lastSyncNever: "尚未同步", syncFilesNote: "登录后可跨设备同步；图书文件本身不会上传", notLoggedIn: "尚未登录", searchBooks: "搜索书籍", shelfSearch: "全书架正文检索", searchPlaceholder: "搜索 书名 / 作者 / 简介", shelfSearchPlaceholder: "全书架正文检索，回车搜索…", clearSearch: "清空搜索", noSearchHistory: "暂无搜索记录" },
    "zh-TW": { syncTitle: "同步", accountLabel: "帳號", password: "密碼", register: "註冊", login: "登入", recoverPassword: "找回密碼", boundEmail: "已綁定的電子郵件", emailCode: "電子郵件驗證碼", newLoginPassword: "新登入密碼（至少 8 個字元）", resetAndLogin: "確認重設並登入", accountPrefix: "帳號：", syncNow: "同步", accountSecurity: "帳戶安全", logout: "登出", syncContent: "同步內容", syncProgress: "閱讀進度與續讀位置", syncReadingData: "書籤、標示、批註、評分、標籤與收藏夾", syncVocabulary: "生詞本", syncStatistics: "閱讀統計", syncTags: "AI 圖書分類標籤", syncApi: "AI 與翻譯 API 設定（不含密鑰）", syncHistory: "智讀與書庫問答記錄（可選）", syncSecrets: "加密 API Key 與翻譯密鑰（可選）", smartReading: "智讀、書庫問答與翻譯", smartReadingHelp: "分類標籤和設定預設同步；問答記錄與加密密鑰可在同步設定中開啟。", syncSettings: "同步設定", lastSync: "最近同步：{time}", lastSyncNever: "尚未同步", syncFilesNote: "登入後可跨裝置同步；圖書檔案本身不會上傳", notLoggedIn: "尚未登入", searchBooks: "搜尋圖書", shelfSearch: "全書架全文檢索", searchPlaceholder: "搜尋 書名 / 作者 / 簡介", shelfSearchPlaceholder: "全書架全文檢索，按 Enter 搜尋…", clearSearch: "清除搜尋", noSearchHistory: "暫無搜尋記錄" },
    en: { syncTitle: "Sync", accountLabel: "Account", password: "Password", register: "Register", login: "Sign in", recoverPassword: "Recover password", boundEmail: "Bound email", emailCode: "Email code", newLoginPassword: "New password (at least 8 characters)", resetAndLogin: "Reset and sign in", accountPrefix: "Account: ", syncNow: "Sync", accountSecurity: "Account security", logout: "Sign out", syncContent: "What syncs", syncProgress: "Reading progress and resume position", syncReadingData: "Bookmarks, highlights, notes, ratings, tags and collections", syncVocabulary: "Vocabulary", syncStatistics: "Reading statistics", syncTags: "AI book classification tags", syncApi: "AI and translation API settings (without secrets)", syncHistory: "AI reading and Library Q&A history (optional)", syncSecrets: "Encrypted API keys and translation secrets (optional)", smartReading: "AI reading, Library Q&A and translation", smartReadingHelp: "Classification tags and settings sync by default. Enable Q&A history and encrypted secrets in Sync settings.", syncSettings: "Sync settings", lastSync: "Last sync: {time}", lastSyncNever: "Never synced", syncFilesNote: "Sign in to sync across devices; book files are never uploaded.", notLoggedIn: "Not signed in", searchBooks: "Search books", shelfSearch: "Full-shelf text search", searchPlaceholder: "Search title / author / description", shelfSearchPlaceholder: "Search the full shelf; press Enter…", clearSearch: "Clear search", noSearchHistory: "No search history" },
    ja: { syncTitle: "同期", accountLabel: "アカウント", password: "パスワード", register: "登録", login: "ログイン", recoverPassword: "パスワードを再設定", boundEmail: "登録済みメール", emailCode: "メール認証コード", newLoginPassword: "新しいパスワード（8文字以上）", resetAndLogin: "再設定してログイン", accountPrefix: "アカウント: ", syncNow: "同期", accountSecurity: "アカウントの安全", logout: "ログアウト", syncContent: "同期内容", syncProgress: "読書進捗と再開位置", syncReadingData: "しおり、ハイライト、注釈、評価、タグとコレクション", syncVocabulary: "単語帳", syncStatistics: "読書統計", syncTags: "AI書籍分類タグ", syncApi: "AI・翻訳 API 設定（秘密情報を除く）", syncHistory: "AI読書とライブラリQ&A履歴（任意）", syncSecrets: "暗号化された API キーと翻訳キー（任意）", smartReading: "AI読書、ライブラリQ&Aと翻訳", smartReadingHelp: "分類タグと設定は既定で同期されます。Q&A履歴と暗号化キーは同期設定で有効にできます。", syncSettings: "同期設定", lastSync: "前回の同期: {time}", lastSyncNever: "未同期", syncFilesNote: "ログインすると端末間で同期できます。本のファイルはアップロードされません。", notLoggedIn: "未ログイン", searchBooks: "本を検索", shelfSearch: "書架全体を全文検索", searchPlaceholder: "書名 / 著者 / 紹介を検索", shelfSearchPlaceholder: "書架全体を検索。Enterで実行…", clearSearch: "検索をクリア", noSearchHistory: "検索履歴はありません" },
    ko: { syncTitle: "동기화", accountLabel: "계정", password: "비밀번호", register: "가입", login: "로그인", recoverPassword: "비밀번호 찾기", boundEmail: "연결된 이메일", emailCode: "이메일 인증 코드", newLoginPassword: "새 비밀번호(8자 이상)", resetAndLogin: "재설정 후 로그인", accountPrefix: "계정: ", syncNow: "동기화", accountSecurity: "계정 보안", logout: "로그아웃", syncContent: "동기화 항목", syncProgress: "읽기 진행률 및 이어 읽기 위치", syncReadingData: "책갈피, 하이라이트, 메모, 평점, 태그 및 컬렉션", syncVocabulary: "단어장", syncStatistics: "독서 통계", syncTags: "AI 책 분류 태그", syncApi: "AI 및 번역 API 설정(비밀 제외)", syncHistory: "AI 읽기 및 라이브러리 Q&A 기록(선택)", syncSecrets: "암호화된 API 키와 번역 키(선택)", smartReading: "AI 읽기, 라이브러리 Q&A 및 번역", smartReadingHelp: "분류 태그와 설정은 기본 동기화됩니다. Q&A 기록과 암호화 키는 동기화 설정에서 켤 수 있습니다.", syncSettings: "동기화 설정", lastSync: "최근 동기화: {time}", lastSyncNever: "동기화한 적 없음", syncFilesNote: "로그인하면 기기 간 동기화할 수 있으며 책 파일은 업로드되지 않습니다.", notLoggedIn: "로그인하지 않음", searchBooks: "책 검색", shelfSearch: "전체 책장 본문 검색", searchPlaceholder: "제목 / 저자 / 설명 검색", shelfSearchPlaceholder: "전체 책장에서 검색, Enter를 누르세요…", clearSearch: "검색 지우기", noSearchHistory: "검색 기록 없음" },
    fr: { syncTitle: "Synchronisation", accountLabel: "Compte", password: "Mot de passe", register: "Créer un compte", login: "Se connecter", recoverPassword: "Récupérer le mot de passe", boundEmail: "E-mail associé", emailCode: "Code reçu par e-mail", newLoginPassword: "Nouveau mot de passe (8 caractères minimum)", resetAndLogin: "Réinitialiser et se connecter", accountPrefix: "Compte : ", syncNow: "Synchroniser", accountSecurity: "Sécurité du compte", logout: "Se déconnecter", syncContent: "Contenu synchronisé", syncProgress: "Progression et position de reprise", syncReadingData: "Marque-pages, surlignages, notes, évaluations, étiquettes et collections", syncVocabulary: "Vocabulaire", syncStatistics: "Statistiques de lecture", syncTags: "Étiquettes de classement IA", syncApi: "Réglages API IA et traduction (sans secrets)", syncHistory: "Historique IA et Q&R de bibliothèque (facultatif)", syncSecrets: "Clés API et clés de traduction chiffrées (facultatif)", smartReading: "Lecture IA, Q&R de bibliothèque et traduction", smartReadingHelp: "Les étiquettes et réglages sont synchronisés par défaut. Activez l’historique et les secrets dans les réglages de synchronisation.", syncSettings: "Réglages de synchronisation", lastSync: "Dernière synchronisation : {time}", lastSyncNever: "Jamais synchronisé", syncFilesNote: "Connectez-vous pour synchroniser vos appareils ; les fichiers de livres ne sont jamais envoyés.", notLoggedIn: "Non connecté", searchBooks: "Rechercher des livres", shelfSearch: "Recherche plein texte de la bibliothèque", searchPlaceholder: "Rechercher titre / auteur / description", shelfSearchPlaceholder: "Rechercher toute la bibliothèque ; Entrée…", clearSearch: "Effacer la recherche", noSearchHistory: "Aucun historique de recherche" },
    de: { syncTitle: "Synchronisierung", accountLabel: "Konto", password: "Passwort", register: "Registrieren", login: "Anmelden", recoverPassword: "Passwort wiederherstellen", boundEmail: "Verknüpfte E-Mail", emailCode: "E-Mail-Code", newLoginPassword: "Neues Passwort (mindestens 8 Zeichen)", resetAndLogin: "Zurücksetzen und anmelden", accountPrefix: "Konto: ", syncNow: "Synchronisieren", accountSecurity: "Kontosicherheit", logout: "Abmelden", syncContent: "Synchronisierte Inhalte", syncProgress: "Lesefortschritt und Fortsetzungsposition", syncReadingData: "Lesezeichen, Markierungen, Notizen, Bewertungen, Tags und Sammlungen", syncVocabulary: "Vokabeln", syncStatistics: "Lesestatistik", syncTags: "KI-Buchklassifizierungs-Tags", syncApi: "KI- und Übersetzungs-API-Einstellungen (ohne Geheimnisse)", syncHistory: "KI-Lese- und Bibliotheksfragen-Verlauf (optional)", syncSecrets: "Verschlüsselte API- und Übersetzungsschlüssel (optional)", smartReading: "KI-Lesen, Bibliotheksfragen und Übersetzung", smartReadingHelp: "Klassifizierungs-Tags und Einstellungen werden standardmäßig synchronisiert. Verlauf und Schlüssel lassen sich in den Synchronisierungseinstellungen aktivieren.", syncSettings: "Synchronisierungseinstellungen", lastSync: "Letzte Synchronisierung: {time}", lastSyncNever: "Noch nie synchronisiert", syncFilesNote: "Melden Sie sich an, um Geräte zu synchronisieren; Buchdateien werden nie hochgeladen.", notLoggedIn: "Nicht angemeldet", searchBooks: "Bücher suchen", shelfSearch: "Volltextsuche in der gesamten Bibliothek", searchPlaceholder: "Titel / Autor / Beschreibung suchen", shelfSearchPlaceholder: "Gesamte Bibliothek durchsuchen; Eingabetaste…", clearSearch: "Suche löschen", noSearchHistory: "Kein Suchverlauf" },
    es: { syncTitle: "Sincronización", accountLabel: "Cuenta", password: "Contraseña", register: "Registrarse", login: "Iniciar sesión", recoverPassword: "Recuperar contraseña", boundEmail: "Correo vinculado", emailCode: "Código de correo", newLoginPassword: "Nueva contraseña (mínimo 8 caracteres)", resetAndLogin: "Restablecer e iniciar sesión", accountPrefix: "Cuenta: ", syncNow: "Sincronizar", accountSecurity: "Seguridad de la cuenta", logout: "Cerrar sesión", syncContent: "Contenido sincronizado", syncProgress: "Progreso de lectura y posición", syncReadingData: "Marcadores, resaltados, notas, valoraciones, etiquetas y colecciones", syncVocabulary: "Vocabulario", syncStatistics: "Estadísticas de lectura", syncTags: "Etiquetas de clasificación con IA", syncApi: "Ajustes de API de IA y traducción (sin secretos)", syncHistory: "Historial de IA y preguntas de biblioteca (opcional)", syncSecrets: "Claves API y de traducción cifradas (opcional)", smartReading: "Lectura IA, preguntas de biblioteca y traducción", smartReadingHelp: "Las etiquetas y ajustes se sincronizan de forma predeterminada. Active el historial y las claves en los ajustes de sincronización.", syncSettings: "Ajustes de sincronización", lastSync: "Última sincronización: {time}", lastSyncNever: "Nunca sincronizado", syncFilesNote: "Inicie sesión para sincronizar dispositivos; los archivos de libros nunca se suben.", notLoggedIn: "Sin sesión iniciada", searchBooks: "Buscar libros", shelfSearch: "Búsqueda de texto en toda la biblioteca", searchPlaceholder: "Buscar título / autor / descripción", shelfSearchPlaceholder: "Buscar en toda la biblioteca; pulse Intro…", clearSearch: "Borrar búsqueda", noSearchHistory: "Sin historial de búsqueda" },
    ru: { syncTitle: "Синхронизация", accountLabel: "Учётная запись", password: "Пароль", register: "Регистрация", login: "Войти", recoverPassword: "Восстановить пароль", boundEmail: "Привязанный e-mail", emailCode: "Код из e-mail", newLoginPassword: "Новый пароль (не менее 8 символов)", resetAndLogin: "Сбросить и войти", accountPrefix: "Учётная запись: ", syncNow: "Синхронизировать", accountSecurity: "Безопасность аккаунта", logout: "Выйти", syncContent: "Синхронизируемые данные", syncProgress: "Прогресс чтения и позиция продолжения", syncReadingData: "Закладки, выделения, заметки, оценки, теги и коллекции", syncVocabulary: "Словарь", syncStatistics: "Статистика чтения", syncTags: "Теги классификации книг ИИ", syncApi: "Настройки ИИ и API перевода (без секретов)", syncHistory: "История ИИ и вопросов к библиотеке (необязательно)", syncSecrets: "Зашифрованные API-ключи и ключи перевода (необязательно)", smartReading: "ИИ-чтение, вопросы к библиотеке и перевод", smartReadingHelp: "Теги классификации и настройки синхронизируются по умолчанию. Историю и ключи можно включить в настройках синхронизации.", syncSettings: "Настройки синхронизации", lastSync: "Последняя синхронизация: {time}", lastSyncNever: "Не синхронизировалось", syncFilesNote: "Войдите для синхронизации между устройствами; файлы книг не загружаются.", notLoggedIn: "Не выполнен вход", searchBooks: "Поиск книг", shelfSearch: "Полнотекстовый поиск по всей библиотеке", searchPlaceholder: "Поиск названия / автора / описания", shelfSearchPlaceholder: "Искать по всей библиотеке; Enter…", clearSearch: "Очистить поиск", noSearchHistory: "Нет истории поиска" },
    "pt-BR": { syncTitle: "Sincronização", accountLabel: "Conta", password: "Senha", register: "Criar conta", login: "Entrar", recoverPassword: "Recuperar senha", boundEmail: "E-mail vinculado", emailCode: "Código por e-mail", newLoginPassword: "Nova senha (ao menos 8 caracteres)", resetAndLogin: "Redefinir e entrar", accountPrefix: "Conta: ", syncNow: "Sincronizar", accountSecurity: "Segurança da conta", logout: "Sair", syncContent: "Conteúdo sincronizado", syncProgress: "Progresso de leitura e posição de retomada", syncReadingData: "Marcadores, destaques, notas, avaliações, etiquetas e coleções", syncVocabulary: "Vocabulário", syncStatistics: "Estatísticas de leitura", syncTags: "Etiquetas de classificação por IA", syncApi: "Configurações de API de IA e tradução (sem segredos)", syncHistory: "Histórico de IA e perguntas da biblioteca (opcional)", syncSecrets: "Chaves de API e tradução criptografadas (opcional)", smartReading: "Leitura por IA, perguntas da biblioteca e tradução", smartReadingHelp: "Etiquetas de classificação e configurações são sincronizadas por padrão. Ative o histórico e as chaves nas configurações de sincronização.", syncSettings: "Configurações de sincronização", lastSync: "Última sincronização: {time}", lastSyncNever: "Nunca sincronizado", syncFilesNote: "Entre para sincronizar dispositivos; os arquivos dos livros nunca são enviados.", notLoggedIn: "Não conectado", searchBooks: "Pesquisar livros", shelfSearch: "Pesquisa de texto em toda a biblioteca", searchPlaceholder: "Pesquisar título / autor / descrição", shelfSearchPlaceholder: "Pesquisar toda a biblioteca; pressione Enter…", clearSearch: "Limpar pesquisa", noSearchHistory: "Sem histórico de pesquisa" }
  };
  Object.entries(ACCOUNT_SEARCH_COPY).forEach(([locale, copy]) => Object.assign(COPY[locale], copy));
  const SYNC_COUNTS_COPY = {
    "zh-CN": "上次尝试上传 {pushed} 项，新增 {accepted} 项，重复/冲突 {ignored} 项，接收 {pulled} 项；图书文件本身不会上传",
    "zh-TW": "上次嘗試上傳 {pushed} 項，新增 {accepted} 項，重複/衝突 {ignored} 項，接收 {pulled} 項；圖書檔案本身不會上傳",
    en: "Last attempt: uploaded {pushed}, added {accepted}, duplicate/conflict {ignored}, received {pulled}; book files are never uploaded.",
    ja: "前回の試行: アップロード {pushed}、追加 {accepted}、重複・競合 {ignored}、受信 {pulled}。本のファイルはアップロードされません。",
    ko: "지난 시도: 업로드 {pushed}, 추가 {accepted}, 중복/충돌 {ignored}, 수신 {pulled}. 책 파일은 업로드되지 않습니다.",
    fr: "Dernière tentative : envoi {pushed}, ajout {accepted}, doublon/conflit {ignored}, réception {pulled}. Les fichiers de livres ne sont jamais envoyés.",
    de: "Letzter Versuch: hochgeladen {pushed}, hinzugefügt {accepted}, Duplikat/Konflikt {ignored}, empfangen {pulled}. Buchdateien werden nie hochgeladen.",
    es: "Último intento: enviados {pushed}, añadidos {accepted}, duplicado/conflicto {ignored}, recibidos {pulled}. Los archivos de libros nunca se suben.",
    ru: "Последняя попытка: отправлено {pushed}, добавлено {accepted}, дубликаты/конфликты {ignored}, получено {pulled}. Файлы книг не загружаются.",
    "pt-BR": "Última tentativa: enviados {pushed}, adicionados {accepted}, duplicados/conflitos {ignored}, recebidos {pulled}. Os arquivos dos livros nunca são enviados."
  };
  Object.entries(SYNC_COUNTS_COPY).forEach(([locale, copy]) => { COPY[locale].syncCounts = copy; });
  const LIBRARY_SELECTOR_COPY = {
    "zh-CN": { libraryScopeTip: "书库问答会精确检索全部已建立语义索引的图书，展示最相关的前 20 本（每本 1 段）。勾选图书后才限定范围；跨书对比请选择 2–8 本。", libraryFilters: "快速筛选图书", tagLabel: "标签", collectionLabel: "收藏夹", libraryFilterTip: "未勾选不代表未参与：书库问答默认检索全部已建立语义索引的图书；勾选才会切换为手动限定范围。", bookSelectorPlaceholder: "搜索书名、作者、简介或标签", scopeAllBooks: "当前范围：全部书库", questionScopeSelected: "当前范围：仅检索已选 {selected} 本{visible}", questionScopeAll: "当前范围：全部书库（未勾选即全库检索，前 {limit} 本命中）", compareScope: "对比范围：已选 {selected}/{limit} 本{visible}", scopeVisible: "（当前显示 {count} 本）", bookCountAll: "书架共 {count} 本", bookCountFiltered: "显示 {visible} / 共 {total} 本", noBookSearchMatches: "没有匹配书名、作者、简介或标签的图书。", unnamedBook: "未命名图书", unknownAuthor: "未知作者", selectionLimitMessage: "{mode}最多选择 {limit} 本图书。" },
    "zh-TW": { libraryScopeTip: "書庫問答會精確檢索全部已建立語意索引的圖書，顯示最相關的前 20 本（每本 1 段）。勾選圖書後才限定範圍；跨書比較請選擇 2–8 本。", libraryFilters: "快速篩選圖書", tagLabel: "標籤", collectionLabel: "收藏夾", libraryFilterTip: "未勾選不代表未參與：書庫問答預設檢索全部已建立語意索引的圖書；勾選才會切換為手動限定範圍。", bookSelectorPlaceholder: "搜尋書名、作者、簡介或標籤", scopeAllBooks: "目前範圍：全部書庫", questionScopeSelected: "目前範圍：僅檢索已選 {selected} 本{visible}", questionScopeAll: "目前範圍：全部書庫（未勾選即全庫檢索，前 {limit} 本命中）", compareScope: "比較範圍：已選 {selected}/{limit} 本{visible}", scopeVisible: "（目前顯示 {count} 本）", bookCountAll: "書架共 {count} 本", bookCountFiltered: "顯示 {visible} / 共 {total} 本", noBookSearchMatches: "沒有符合書名、作者、簡介或標籤的圖書。", unnamedBook: "未命名圖書", unknownAuthor: "未知作者", selectionLimitMessage: "{mode}最多選擇 {limit} 本圖書。" },
    en: { libraryScopeTip: "Library Q&A searches every book with a semantic index and shows the 20 most relevant books (one passage each). Checking books limits the scope; choose 2–8 books for comparison.", libraryFilters: "Quick book filters", tagLabel: "Tags", collectionLabel: "Collections", libraryFilterTip: "Unchecked books still participate: Library Q&A searches every indexed book by default. Checking books switches to a manual scope.", bookSelectorPlaceholder: "Search title, author, description, or tags", scopeAllBooks: "Current scope: Entire library", questionScopeSelected: "Current scope: {selected} selected book(s){visible}", questionScopeAll: "Current scope: Entire library (all indexed books; top {limit} matches)", compareScope: "Comparison scope: {selected}/{limit} book(s){visible}", scopeVisible: " ({count} currently shown)", bookCountAll: "{count} books on shelf", bookCountFiltered: "Showing {visible} of {total} books", noBookSearchMatches: "No books match the title, author, description, or tags.", unnamedBook: "Untitled book", unknownAuthor: "Unknown author", selectionLimitMessage: "{mode} supports up to {limit} books." }
  };
  Object.entries(LIBRARY_SELECTOR_COPY).forEach(([locale, copy]) => Object.assign(COPY[locale], copy));
  function selectedLanguage() { return localStorage.getItem(STORAGE_KEY) || "system"; }
  function resolvedLanguage() {
    const selected = selectedLanguage();
    if (selected !== "system") return selected;
    const system = String(navigator.language || "zh-CN").toLowerCase();
    if (system.startsWith("zh-tw") || system.startsWith("zh-hk") || system.startsWith("zh-mo")) return "zh-TW";
    const exact = LANGUAGES.map((item) => item[0]).find((item) => item.toLowerCase() === system);
    return exact || (system.split("-")[0] === "zh" ? "zh-CN" : system.split("-")[0]);
  }
  function t(key) { return (COPY[resolvedLanguage()] || COPY.en)[key] || COPY.en[key] || COPY["zh-CN"][key] || key; }
  function apply(root) {
    const language = resolvedLanguage();
    document.documentElement.lang = language;
    (root || document).querySelectorAll?.("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
    (root || document).querySelectorAll?.("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
    (root || document).querySelectorAll?.("[data-i18n-title]").forEach((element) => { element.title = t(element.dataset.i18nTitle); });
    (root || document).querySelectorAll?.("[data-i18n-aria]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAria)); });
  }
  function populate(select) {
    if (!select) return;
    select.replaceChildren(...LANGUAGES.map(([value, label]) => {
      const option = document.createElement("option"); option.value = value; option.textContent = value === "system" ? t("followSystem") : label; return option;
    }));
    select.value = selectedLanguage();
  }
  function setLanguage(value) {
    localStorage.setItem(STORAGE_KEY, LANGUAGES.some(([id]) => id === value) ? value : "system");
    apply(document);
    document.querySelectorAll(".app-language-select").forEach(populate);
    global.dispatchEvent(new CustomEvent("app-language-changed", { detail: { selected: selectedLanguage(), resolved: resolvedLanguage() } }));
  }
  global.ReaderAppI18n = { STORAGE_KEY, apply, populate, selectedLanguage, resolvedLanguage, setLanguage, t };
  document.addEventListener("DOMContentLoaded", () => apply(document), { once: true });
})(window);
